### ISSUE TITLE
Song of the wild not working with creatures played after it

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#1125]
My opponent had speed sigil out. I played song of the Wild then played feather shaman and reaped with her. I also reaped with a creature that was already in play at the start of the turn. The extra amber was from song of the wild was only given for the latter reap

My guess is that lasting effects are not working correctly. They should apply also to creatures that were played after the lasting effect was applied, so long as those creatures were played during the time the lasting effect affects. The relevant rules text is the following:

> Some card abilities create effects or conditions that affect the game for a specified period of time, such as “until the start of your next turn” or “for the remainder of the turn.” These are called lasting effects.

> Lasting effects are treated as constant abilities that are active for the duration specified by the effect. A lasting effect persists even if the card that created the effect leaves play.

> **If a lasting effect affects cards in play, it applies to all cards in play during the specified period, regardless of whether they were in play at the time the lasting effect was established.** 

The log for the game is attached as a text file. The bug happened on turn 9.
[song of the wild not working with creatures played after it.txt](https://github.com/keyteki/keyteki/files/4170235/song.of.the.wild.not.working.with.creatures.played.after.it.txt)

**Comment by hydrophilic-attack** [comment]
I'm guessing this is the root cause off issue #995

**Comment by jtrussell** [comment]
I'd be curious to get an official ruling on this one - you're right that SotW sets up a last effect, but I think the wording limits the scope of the lasting effect to the creatures in play at the time SotW is played. 

Contrast with something like Barn Razing:

> Play: For the remainder of the turn, your opponent loses 1A each time a friendly creature fights.

Lasting effects tend to follow the template of `[choices, ][duration], [effect]`. With SotW, the effect is granting an ability to the creatures in play at the time, for Barn Razing it's setting up a trigger for when a particular game action occurs.

**Comment by hydrophilic-attack** [comment]
@jtrussell 

I think that is covered by the rules snippet I quoted and bolded:

> If a lasting effect affects cards in play, it applies to all cards in play during the specified period, regardless of whether they were in play at the time the lasting effect was established.

**Comment by jtrussell** [comment]
If the card read:

> Play: Each friendly creature gains, “Reap: Gain 1A."

I.e. if the reap ability was granted indefinitely, I think it's more clear that subsequently played creatures won't get the reap ability. The granting happens at the time SotW is played, how long you get to keep that reap ability is set by the duration - in this case the remainder of the turn. I'd agree that all cards in play are affected by the lasting effect, but unless they were around at the time SotW was played, they won't get much benefit from it.

Similarly, if it had been worded:

> For the remainder of the turn, gain 1A each time a friendly creature reaps.

That would also cover creatures played after. Even if it said "Each friendly creature **has**..." instead of "Each friendly creatures **gains**... " I'd be more inclined to agree with you.

You could easily be right, but without a ruling from the folks at FFG I'd argue that `each creature gains X` happens at a point in time (even if you lose X after a duration) whereas `whenever a creature Xs do Y` is the template that covers the behavior you're hoping for.

**Comment by blinkingline** [comment]
The lasting effect should apply regardless if creatures are in play or not, based on the very definition of [lasting effects](https://archonarcana.com/Lasting_effects). 

For further evidence that this is the case, look at the clarifications provided by FFG for [Shadow of Dis](https://archonarcana.com/Shadow_of_Dis). If lasting effects only applied to creatures that were in play, then FFG would have had no need to clarify how Shadow of Dis applies to things like playing [Silvertooth](https://archonarcana.com/Silvertooth), [Alpha](https://archonarcana.com/Alpha), and [Omega](https://archonarcana.com/Omega) cards.

**Comment by jtrussell** [comment]
The distinction is between things like "creatures **gain**..." vs "creatures **have**..." (or "text boxes **are**...". The former bestows an ability at a point in time, the latter sets up a new game rule.

SotW is tricky because it wraps a lasting effect around a point in time granting of an ability. The lasting effect applies to all creatures, but the bestowed ability is only applied to creatures in play at the time you play SotW.

Shadow if Dis isn't quite the same as it create a new game rule as opposed to granting creatures an ability.

Consider a potential alternate wording for SotW: "Each friendly creature **has** Reap: Gain 1A". This would match Shadow of Dis by setting up a new game rule as opposed to the current wording that grants a new reap ability at a point in time, and it would apply to creatures played after SotW.

**Comment by blinkingline** [comment]
The person who rose the initial issue cited the rules for lasting effects, including the text rules that state:
"If a lasting effect affects cards in play, it applies to all cards in play during the specified period, **regardless of whether they were in play at the time the lasting effect was established.**"

You then replied, "It'd be nice to have an official ruling". 

I provide a card that clearly shows that lasting effects don't care if the card was in play or not. You choose to sweep that aside as well. 

You're making this about the specific effect of gaining an ability, but there's no reason that it should act any differently from any other lasting effect.

If lasting effects didn't work in the way that OP and I have described it, why would a card like [Charge!](https://archonarcana.com/Charge!) even exist?

**Comment by hydrophilic-attack** [comment]
@jtrussell , if I'm reading your argument correctly it hinges on the specific wording of Song of the Wild. Specifically that includes the word "gains"

So I ask you this, if I play Diplo-Macy on my turn, and you next turn play a stilt-kin and a ganger chieftain to fight with the stilt-kin twice, would you not need to exalt stilt-kin twice?

**Comment by jtrussell** [comment]
From a quick test, it looks like Diplo-Macy currently grants the the **Before Fight** ability to creatures played afterward. So that's at least an inconsistency :).

**Comment by hydrophilic-attack** [comment]
well, i sure hope that the outcome of this discussion won't be that you change diplo-macy to work incorrectly as well :)

**Comment by jtrussell** [comment]
Hah! Honestly, I think I'm coming around to agreeing with you - maybe considering SotW as something like Kangaphant or Uncharted Lands but as a lasting effect rather than a creature. What hangs me up is why they wouldn't use the Crystal Hive wording which does (effectively) the same thing and very clearly applies to creatures regardless of when they're played. It sets up a new game effect rather than granting the ability to creatures.

**Comment by hydrophilic-attack** [comment]
A possible reason for why Crystal Hive and 
Song of the Wild are worded differently ways is that one of them was written before the section on lasting effects was added to the official rules while the other was written after that section was added to the official rules 

In general, one shouldn't pay too much heed to subtle differences in wording between different sets. A quick look at the credits for each set (included in the quickstart rules one gets with starter sets) shows that the staff doing editing and proofreading changes for each new set.

**Comment by Achocholacek** [comment]
This is definitely a bug and we'll need to evaluate a number of our lasting effect cards to account for the (very thorough) discussion that's gone on here.

**Comment by mcarulli** [comment]
Not sure if it's helpful but this happened to me in a game today with Moor Wolves and 2x song of the wild on the same turn. 
![image](https://user-images.githubusercontent.com/40010247/86074211-7965fb80-ba53-11ea-8422-66498d0bcc15.png)
[song of the wild bug.txt](https://github.com/keyteki/keyteki/files/4848978/song.of.the.wild.bug.txt)
