### ISSUE TITLE
When Reassembling Automaton dies an infinite loop occurs

### ISSUE THREAD

**Issue by Organwolf** [keyteki/keyteki#1478]
It might be a problem that is specific to my deck but I have a [Reassembling Automaton](https://aember-forge.com/card/reassembling-automaton) together with [Spartasaur](https://aember-forge.com/card/spartasaur) and when they both are on the table and the Automaton dies I/or my opponent get prompted to play him to the left or right indefinetely. This problem/bug must have occured recently as I've been playing with this deck a lot for a long time and it's first now that I'm encountering this problem.

**Comment by drallieiv** [comment]
The instead of Reassembling Automaton seems to not be handled properly.
In the timing the "Destroy" should trigger before the "After is destroyed".
And the Automaton effect is a replacement, so it should cancel the initial Destroy.

Check "Self-Bolstering Automata" too.

Seems that the way events are currently handled, there is no difference between how the "destroyed" event is handled (onCardDestroyed) and the after, which drops if there is a replacement (changeEvent).

Other cases, when Automata/Automaton destroyed is replaced :
Pïle of Skull, Soul Snatcher, Tolas, Neffru, Nizak, Loot ther bodies, Looter Goblin, Warchest, and Foozle should not trigger 
Overrun should not count +1
The Colosseum should not receive a counter

Automaton tests should also check that any token (captured/exalter aember, damage, and stun) stays on it.
