### ISSUE TITLE
Soft landing does not ready 

### ISSUE THREAD

**Issue by mountainsine** [keyteki/keyteki#1517]
**Summary:**
After playing the card Soft Landing followed by John Smyth The card "John Smyth" does not enter the battlefield ready (screenshot attached)

**Expected:**
After playing the card soft landing "John Smyth" should enter the battlefield ready.

**Environement:**
Production 5-26-20 10:30 am
MacOS 10.15.4 - Chrome 81.0.4044.138 (Official Build) (64-bit)

<img width="659" alt="1517" src="https://user-images.githubusercontent.com/12061652/82922372-21614400-9f3f-11ea-8df9-cde22f6789d6.png">

**Comment by LifeIsPizza** [comment]
I've managed to reproduce the issue. It happens when you have a Tunk in play and you get the prompt as you play a Mars creature if you want to heal Tunk first or trigger Soft Landing. If you choose the latter first, everything works fine, but if you choose the former, Soft Landing's effect somehow fizzles.

Blypyp, who has a similar effect, has the same bug.

**Comment by mountainsine** [comment]
Thanks for fixing this bug. I like mars.
