### ISSUE TITLE
One Stood Against Many on a stunned creature vs. two targets

### ISSUE THREAD

**Issue by alexander-rymasheusky** [keyteki/keyteki#1545]
I have a stunned Zorg. My opponent has Doc Bookton and Titan Mechanic.

I play One Stood Against Many.  

Expected: According to this post in the funny thread
https://community.fantasyflightgames.com/topic/287591-one-stood-against-many-question/?do=findComment&comment=3585885  and my own understanding, I choose Titan Mechanic, stun clears, I choose Doc Bookton, fight happens; then (I'm not sure which) Zorg readies or doesn't ready, but cannot fight TM.

Actual: stunned Zorg fights Doc Bookton, readies and fight Titan Mechanic, both die.

**Comment by SkyJedi** [comment]
OSAM is bugged and reported already #241

**Comment by alexander-rymasheusky** [comment]
Good on you to chime in, but I describe a different situation from #241.  A person who's in charge of fixing it would be better served with an additional scenario rather than just two described there.

**Comment by cryogen** [comment]
@alexander-rymasheusky Thank you for the report. It's ok, this one is now linked to that so we have the info. The fact is OSAM is implemented very poorly so has a number of issues caused by that poor implementation. Fixing it will fix all of those issues at once. Sadly it's not an easy fix which is why it's still broken
