### ISSUE TITLE
"Fanghouse" vs "Fanghouse"

### ISSUE THREAD

**Issue by UltraUltraUltra** [keyteki/keyteki#1546]
When two players both have a "Fanghouse" in play neither player appears to be prompted to choose the order of the Assault / Hazardous damage.

It also appears that the damage works differently for the two players, so if player A attacks Player B's "Fanghouse" with their "Fanghouse", Player A's "Fanghouse" will kill Player's B "Fanghouse" (without a prompt and without receiving any Hazardous damage) but if Player B's "Fanghouse" attacks Player A's "Fanghouse", Player B's "Fanghouse" will be killed by Player's A "Fanghouse" without doing any Assault damage (nor being prompted to order either of the two damages).

**Comment by romanogit** [comment]
Do you have "Prompt for simultaneous abilities" checked in your profile (Go to Profile, scroll all the way to the bottom)? If not, the platform will resolve those abilities automatically, but not necessarily always in your favor.

**Comment by UltraUltraUltra** [comment]
Yes, I do have it checked.  Apologies for not stating that in my original post.

**Comment by romanogit** [comment]
Maybe the interrupt was not clear:

![image](https://user-images.githubusercontent.com/2104075/86658099-29d97f80-bfbf-11ea-830b-fbcb057671fd.png)

if you have to have this options set:

![image](https://user-images.githubusercontent.com/2104075/86658177-3958c880-bfbf-11ea-86da-13ad051e2548.png)

![image](https://user-images.githubusercontent.com/2104075/86658221-42499a00-bfbf-11ea-9315-12a429b06e01.png)

This issue is working as expected
