### ISSUE TITLE
Purify put half of Ultra-Gravitron into play

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#1816]
![image](https://user-images.githubusercontent.com/2104075/87967414-24873500-ca95-11ea-97ab-b82b3e4949f4.png)

The creature purged was Deusillus, btw 

(Report from discord)

**Comment by roeswood** [comment]
Happened in my game, too, here's the log:
Mibluffin won the flip and is first player
moonroof is playing as the Archon: S. Eisen, Averinstin’s Shocking Prophet
Mibluffin is playing as the Archon: The Inchoate Web Keeper of Floregus
 Mibluffin has connected to the game server
 moonroof has connected to the game server
Mibluffin
GL
moonroof is shuffling their deck
moonroof draws 6 card  s to their maximum of 6
Mibluffin is shuffling their deck
Mibluffin draws 6 card  s to their maximum of 6
Mibluffin draws 1 card 
Key phase - Mibluffin
Mibluffin does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Mibluffin
Mibluffin chooses shadows  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Shoulder Id
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
End of turn 1
moonroof: 0 Æmber  (0 keys) Mibluffin: 0 Æmber  (0 keys)
Turn 1
Key phase - moonroof
moonroof does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - moonroof
moonroof chooses logos  as their active house this turn
Main phase - moonroof
moonroof plays Eclectic Inquiry
moonroof gains an Æmber  due to Eclectic Inquiry's bonus icon
moonroof uses Eclectic Inquiry to archive the top two cards  of their deck
moonroof plays Bot Bookton
moonroof plays Even Ivan
Ready phase - moonroof
moonroof readies all of their cards 
Draw phase - moonroof
moonroof draws 3 card  s to their maximum of 6
End of turn 1
moonroof: 1 Æmber  (0 keys) Mibluffin: 0 Æmber  (0 keys)
Turn 2
Key phase - Mibluffin
Mibluffin does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Mibluffin
Mibluffin chooses sanctum  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Fangs of Gizelhart
Mibluffin gains an Æmber  due to Fangs of Gizelhart's bonus icon
Mibluffin uses Fangs of Gizelhart to purge Shoulder Id
Mibluffin plays Gizelhart’s Zealot
Mibluffin captures an Æmber  on Gizelhart’s Zealot due to Gizelhart’s Zealot's bonus icon
Mibluffin uses Gizelhart’s Zealot to make Gizelhart’s Zealot fight Bot Bookton
Mibluffin plays Honorable Claim
Mibluffin gains an Æmber  due to Honorable Claim's bonus icon
Mibluffin plays Call to Action
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
Mibluffin draws 4 card  s to their maximum of 6
End of turn 2
moonroof: 1 Æmber  (0 keys) Mibluffin: 2 Æmber  (0 keys)
Turn 2
Key phase - moonroof
moonroof does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - moonroof
moonroof chooses logos  as their active house this turn
Main phase - moonroof
moonroof uses Even Ivan to steal 1 Æmber  from Mibluffin
moonroof plays Diametric Charge
moonroof gains an Æmber  due to Diametric Charge's bonus icon
moonroof uses Diametric Charge to deal 1 damage to Even Ivan and 2 to their neighbors
moonroof plays Ultra Gravitron
moonroof draws a card  due to Ultra Gravitron's bonus icon
moonroof uses Ultra Gravitron to archive 5 cards 
Ready phase - moonroof
moonroof readies all of their cards 
Draw phase - moonroof
moonroof draws 2 card  s to their maximum of 6
End of turn 2
moonroof: 3 Æmber  (0 keys) Mibluffin: 1 Æmber  (0 keys)
Turn 3
Key phase - Mibluffin
Mibluffin does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Mibluffin
Mibluffin chooses shadows  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Look Over There!
Mibluffin uses Look Over There! to deal 2 damage to Even Ivan
Mibluffin plays Perplexing Sophistry
Mibluffin gains an Æmber  due to Perplexing Sophistry's bonus icon
Mibluffin deals 1 damage to Even Ivan due to Perplexing Sophistry's bonus icon
Mibluffin draws a card  due to Perplexing Sophistry's bonus icon
Mibluffin uses Perplexing Sophistry to draw 1 cards 
Mibluffin draws 1 card 
moonroof discards Dark Faerie at random
Mibluffin plays Look Over There!
Mibluffin uses Look Over There! to deal 2 damage to Ultra Gravitron
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
Mibluffin draws 1 card  to their maximum of 6
End of turn 3
moonroof: 1 Æmber  (0 keys) Mibluffin: 4 Æmber  (0 keys)
Turn 3
Key phase - moonroof
moonroof does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - moonroof
moonroof chooses saurian  as their active house this turn
Main phase - moonroof
moonroof plays Saurian Egg
moonroof gains an Æmber  due to Saurian Egg's bonus icon
moonroof plays Citizen Shrix
moonroof gains an Æmber  due to Citizen Shrix's bonus icon
moonroof uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
moonroof plays Galeatops
Ready phase - moonroof
moonroof readies all of their cards 
Draw phase - moonroof
moonroof draws 4 card  s to their maximum of 6
End of turn 3
moonroof: 4 Æmber  (0 keys) Mibluffin: 3 Æmber  (0 keys)
Turn 4
Key phase - Mibluffin
Mibluffin does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - Mibluffin
Mibluffin chooses saurian  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Citizen Shrix
Mibluffin deals 1 damage to Galeatops due to Citizen Shrix's bonus icon
Mibluffin uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
Mibluffin plays Chant of Hubris
Mibluffin gains an Æmber  due to Chant of Hubris's bonus icon
Mibluffin uses Chant of Hubris to remove 1 Æmber  from Citizen Shrix
Mibluffin uses Chant of Hubris to place 1 Æmber  on Citizen Shrix
Mibluffin plays Techno-Saurus
Mibluffin uses Techno-Saurus to exalt Techno-Saurus
Mibluffin plays Amphora Captura
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
Mibluffin draws 4 card  s to their maximum of 6
 Mibluffin declares Check!
End of turn 4
moonroof: 3 Æmber  (0 keys) Mibluffin: 7 Æmber  (0 keys)
Turn 4
Key phase - moonroof
moonroof does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - moonroof
moonroof chooses saurian  as their active house this turn
moonroof moves all the cards  in their archives to their hand
Main phase - moonroof
moonroof plays Xeno-Saurus
moonroof deals 1 damage to Techno-Saurus due to Xeno-Saurus's bonus icon
moonroof uses Xeno-Saurus to exalt Xeno-Saurus
moonroof plays Sagittarii's Gaze
moonroof gains an Æmber  due to Sagittarii's Gaze's bonus icon
moonroof uses Sagittarii's Gaze to exalt Techno-Saurus
moonroof plays Charybdis
moonroof plays Citizen Shrix
moonroof gains an Æmber  due to Citizen Shrix's bonus icon
moonroof uses Citizen Shrix to exalt Citizen Shrix and steal 1 Æmber 
moonroof uses Saurian Egg to discard Infomorph and Resurgence
moonroof uses Galeatops to make Galeatops fight Techno-Saurus
Ready phase - moonroof
moonroof readies all of their cards 
Draw phase - moonroof
 moonroof declares Check!
End of turn 4
moonroof: 8 Æmber  (0 keys) Mibluffin: 6 Æmber  (0 keys)
Turn 5
Key phase - Mibluffin
Mibluffin forges the red key  , paying 6 Æmber 
House phase - Mibluffin
Mibluffin chooses shadows  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Dark Wave
Mibluffin gains an Æmber  due to Dark Wave's bonus icon
Mibluffin uses Dark Wave to deal 2 damage to all non-Mutant creatures
Mibluffin plays Tempting Offer
Mibluffin gains an Æmber  due to Tempting Offer's bonus icon
Mibluffin uses Tempting Offer to return Citizen Shrix to their hand
Mibluffin plays Mutant Cutpurse
Mibluffin deals 1 damage to Charybdis due to Mutant Cutpurse's bonus icon
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
Mibluffin draws 3 card  s to their maximum of 6
End of turn 5
moonroof: 9 Æmber  (0 keys) Mibluffin: 3 Æmber  (1 key)
Turn 5
Key phase - moonroof
moonroof forges the blue key  , paying 6 Æmber 
House phase - moonroof
moonroof chooses untamed  as their active house this turn
Main phase - moonroof
moonroof plays Pismire
moonroof uses Saurian Egg to discard Consul Primus and Scylla
moonroof plays Lost in the Woods
moonroof gains an Æmber  due to Lost in the Woods's bonus icon
moonroof uses Lost in the Woods to shuffle Galeatops and Ultra Gravitron and Mutant Cutpurse into their owner's deck
moonroof plays Dark Faerie
moonroof deals 1 damage to Scylla due to Dark Faerie's bonus icon
moonroof draws a card  due to Dark Faerie's bonus icon
moonroof plays Pismire
moonroof plays Fandangle
moonroof plays Gloriana's Attendant
moonroof plays Earthbind attaching it to Gloriana's Attendant
moonroof gains an Æmber  due to Earthbind's bonus icon
moonroof plays Wild Spirit attaching it to Consul Primus
moonroof gains an Æmber  due to Wild Spirit's bonus icon
moonroof captures an Æmber  on Consul Primus due to Wild Spirit's bonus icon
Ready phase - moonroof
moonroof readies all of their cards 
Draw phase - moonroof
moonroof draws 3 card  s to their maximum of 6
 moonroof declares Check!
End of turn 5
moonroof: 6 Æmber  (1 key) Mibluffin: 2 Æmber  (1 key)
Turn 6
Key phase - Mibluffin
Mibluffin does not forge a key. They have 2 amber. The current cost is 10 Æmber 
House phase - Mibluffin
Mibluffin chooses sanctum  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Purify
Mibluffin gains an Æmber  due to Purify's bonus icon
Mibluffin gains an Æmber  due to Purify's bonus icon
Mibluffin uses Purify to purge Fandangle
Mibluffin takes Ultra Gravitron into their hand
Mibluffin
I don’t think that should have happenned
Mibluffin plays Squire Alys
moonroof
no
 moonroof is attempting to switch manual mode on
 Mibluffin allows enabling manual mode
 moonroof switches manual mode on
Mibluffin draws a card  due to Squire Alys's bonus icon
Mibluffin uses Squire Alys to capture 2 Æmber  from their opponent , placing it on Squire Alys
 moonroof manually moves Ultra Gravitron from their play area to their deck
 moonroof switches manual mode off
Mibluffin
Thanks
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
Mibluffin draws 1 card  to their maximum of 6
End of turn 6
moonroof: 4 Æmber  (1 key) Mibluffin: 4 Æmber  (1 key)
Turn 6
Key phase - moonroof
moonroof does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - moonroof
moonroof chooses untamed  as their active house this turn
Main phase - moonroof
moonroof plays Low Dawn
moonroof gains an Æmber  due to Low Dawn's bonus icon
moonroof captures an Æmber  on Scylla due to Low Dawn's bonus icon
moonroof uses Low Dawn to return Dark Faerie to their deck
moonroof uses Dark Faerie to make Dark Faerie fight Squire Alys
moonroof uses Dark Faerie to gain 2 Æmber 
moonroof uses Pismire to make Pismire fight Squire Alys
moonroof uses Pismire to reap with Pismire
Ready phase - moonroof
moonroof readies all of their cards 
Draw phase - moonroof
moonroof draws 1 card  to their maximum of 6
 moonroof declares Check!
End of turn 6
moonroof: 10 Æmber  (1 key) Mibluffin: 3 Æmber  (1 key)
Turn 7
Key phase - Mibluffin
Mibluffin does not forge a key. They have 3 amber. The current cost is 10 Æmber 
House phase - Mibluffin
Mibluffin chooses shadows  as their active house this turn
Main phase - Mibluffin
Mibluffin plays Rad Penny
Mibluffin deals 1 damage to Dark Faerie due to Rad Penny's bonus icon
Mibluffin uses Rad Penny to steal 1 Æmber  from moonroof
Mibluffin plays "Borrow"
Mibluffin gains an Æmber  due to "Borrow"'s bonus icon
Mibluffin plays Opportunist attaching it to Rad Penny
Mibluffin gains an Æmber  due to Opportunist's bonus icon
Mibluffin uses Opportunist to capture 1 Æmber  from moonroof, placing it on Rad Penny
Ready phase - Mibluffin
Mibluffin readies all of their cards 
Draw phase - Mibluffin
Mibluffin draws 3 card  s to their maximum of 6
End of turn 7
moonroof: 8 Æmber  (1 key) Mibluffin: 6 Æmber  (1 key)
Turn 7
Key phase - moonroof
moonroof forges the yellow key  , paying 6 Æmber 
House phase - moonroof
Mibluffin
Gg
 Mibluffin concedes
 moonroof has won the game
moonroof
gg
 Mibluffin has left the game

**Comment by cryogen** [comment]
#1886
