### ISSUE TITLE
In Adaptive short add record of who brought which deck to chat

### ISSUE THREAD

**Issue by poeticmatter** [keyteki/keyteki#1859]
When looking over the log it is impossible to know who brought which deck, which is important for streaming!

**Comment by SkyJedi** [comment]
on it.

I'm thinking Pre bidding 
> [Player Name 1] brings [deck name X] to the match

post selections and bidding 
> [Player Name 1] will play [deck name X]

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/88470079-d5d70200-cebd-11ea-8dae-9e8b92eb04bb.png)
thoughts?

**Comment by poeticmatter** [comment]
Perfect!

**Comment by 3Mpb** [comment]
Just to add, if both players pick the same deck, you can already tell which player brought which deck because the owner of the deck being bid on starts the bidding with 0.  I recognise this isn't quite as clear as in the proposal of SkyJedi and does not cover the situation where players pick different decks, however.
