### ISSUE TITLE
Aemberlution appeared to leave a ghost of Deusillus in play

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#1927]
Last night, my opponent played Aemberlution when I had Deusillus on board. A very strange thing happened: Deusillus appeared to stay on the board, but I couldn't interact with him.

**Log:**

Main phase - TheTerror987
Tutenkharnage
Yep!
TheTerror987 plays Æmberlution
TheTerror987 uses Æmberlution to destroy each creature; reveal TheTerror987's hand as Munchling, Entropic Swirl, Forge Compiler, Sacro-Bot, and Gleeful Mayhem; and reveal Tutenkharnage's hand as Gizelhart’s Standard, Gizelhart’s Zealot, Red Alert, Access Denied, Gizelhart’s Zealot, and Spoils of Battle and put creatures from each player's hand into play ready
TheTerror987 played Æmberlution which has Omega, ending this step

**Resulting board:**

![image](https://user-images.githubusercontent.com/47071426/91055170-4de63400-e5f2-11ea-8f14-cc56a30b8f43.png)

I know it was destroyed because all its aember went back to my opponent. The menus are legacies from my attempts to select Deusillus in manual mode; I couldn't, so this is the picture after I selected my opponent's Sacro-Bot and one of my two copies of Gizelhart's Zealot, both of which had to fight. (You can see these creatures atop their owner's discard piles.)

It's important to note that if you add up my artifacts, the cards in my hand, and the cards in my draw, discard, and purged piles, you get 36 cards, so I'm confident Deusillus was NOT actually in play.

My opponent saw the same thing I did: a Deusillus, stripped of all the aember it had captured. When I ended my turn, however, I saw something entirely different:

![image](https://user-images.githubusercontent.com/47071426/91055433-a9b0bd00-e5f2-11ea-8ad9-f74cd0541f54.png)

My opponent told me he did not see Deusillus at all after I ended my turn. I had drawn into the top half of Deusillus after a reshuffle, as you can see in my hand. I opened my draw pile and found the bottom half in there, so both cards appeared to have been in my deck, as expected.

**Comment by UltraUltraUltra** [comment]
I had a similar problem.

I had a Deusillus on the board and both halves of another one in my hand (my deck has two copies of Deusillus).  I played Aemberlution and end-up with four copies of Deusillus (8 cards in total) on the board.  The one on the board at the start of turn had an Encounter Suit attached (the one with aember on it), which is why it was not destroyed, so there should have been two when Aemberlution resolved, but definitely not four.

![image](https://user-images.githubusercontent.com/55008319/94873524-5af31000-0447-11eb-9e75-b5e95c0b6a5a.png)

**Comment by romanogit** [comment]
Fixed
