### ISSUE TITLE
Ransack doesn't discard when it doesn't steal

### ISSUE THREAD

**Issue by dukman00** [keyteki/keyteki#1944]
If opponent has no aember, Ransack doesn't discard the top card of the deck. As far as I understand it, it should always discard at least 1 card, and should keep discarding as long as it hits Shadows cards, regardless if any steal happened or not.

**Comment by Tutenkharnage** [comment]
This also during a game I played tonight. My opponent played Ransack last in turn 3 with only two cards in his discard: Fangs of Gizelhart and Cleansing Wave. After he played Ransack and ended his turn, his discard had only three cards in it: Fangs of Gizelhart, Cleansing Wave, and Ransack.

---

End of turn 3
EsquireJJR: 0 Æmber  (0 keys) Tutenkharnage: 1 Æmber  (0 keys)
TURN 3
Key phase - EsquireJJR
EsquireJJR does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - EsquireJJR
EsquireJJR chooses shadows  as their active house this turn
Main phase - EsquireJJR
EsquireJJR plays Spike Trap
EsquireJJR gains an Æmber  due to Spike Trap's bonus icon
EsquireJJR captures an Æmber  on Squire Alys due to Spike Trap's bonus icon
EsquireJJR plays Nexus
EsquireJJR plays Boss Zarek
EsquireJJR plays Ransack
Ready phase - EsquireJJR
EsquireJJR readies all of their cards
