### ISSUE TITLE
Choose ordering for Kirby and Val

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#2265]
When playing cards off of Subject Kirby and Val Jericho, you can end up in situations where you have both effects available at the same time, and then play a creature off of Kirby's effect, which makes Val off-center.

If I'm not mistaken, you should be able to choose the order in which the effects are consumed - so I could use Val's effect first, and then Kirby's.

Maybe I am mistaken and the effects go in a FIFO stack?

**Comment by blinkingline** [comment]
[Captain Val Jericho's (CVJ)](https://archonarcana.com/Captain_Val_Jericho) ability can ONLY be resolved when it is in the center of the battleline. If resolving the play from another card effect shift's CVJ from the center of the battleline, that ability is no longer available to be resolved. This may seem like the abilities are not being resolved properly, when in fact, one of the abiliites is no longer available to be resolved. 

For example, in my battleline, I have two creatures; CVJ on the left and another creature to CVJ's right.  If I play [Subject Kirby](https://archonarcana.com/Subject_Kirby) to the left of CVJ, CVJ's ability becomes active, because CVJ is in the center of the battleline.  However, before a card can be played to use CVJ's ability, the **Play:** ability of Subject Kirby must be resolved, resulting in CVJ moving out of the center of the battleline.  Since CVJ is no longer in the center of the battleline, its ability can no longer be resolved. 

Essentially, you can't interrupt the resolution of the **Play**: ability of Subject Kirby to utilize the ability granted (temporarily) by CVJ.

**Comment by romanogit** [comment]
similar to #947
