### ISSUE TITLE
Champions Challenge does not ready creature 

### ISSUE THREAD

**Issue by MorgothNL** [keyteki/keyteki#246]
Hi, I just played a game where I used Champion's Challenge when the opponent did not have any creatures left. The last sentence on the card says 'ready and fight with your remaining creature', so my creature should have been readied.. for me to be able to reap with it after (since there was no opponent to fight with). Same mechanic as Gauntlet of Command use on a friendly creature without an enemy creature to fight with.

**Comment by gluepan1** [comment]
The reap option shouldn't be available because if it says ready and fight with creature, since there was no target then the cards action was complete. If the cards action was 'ready creature' then that would be allowed because a ready card can reap, attack , or use action if it has one. I've had a lot of games where reaping was done instead of fighting when  it specify otherwise so i m hoping this gets corrected. An easy example of this type of error: if I use keycharge to create a key at +1 cost I can't jus ignore the cards txt and forge a key at six ember, because that's the only ember I have. So just like if a card says' ready and fight ' I can't ignore the txt and reap with the creature that was readied if since there was no target available.

**Comment by MorgothNL** [comment]
Sorry but no, this 'ready and fight' has been 100% cleared up by FFS in the rules and FAQ. Basically you have to do as much as possible. So if it says 'ready and fight' -> you ready -> fight -> no target? -> then do whatever else you want to do with it, but it certainly was readied.

**Comment by Achocholacek** [comment]
@MorgothNL is correct.

The other thing that I will add, however, is that if it is a card that allows you to ready and fight with a creature, with no opposing creatures, and you use it to ready an off-house creature, you DON'T get to then reap with that creature, but it does stay ready.

On-house, though?

Yeah, reap away.

**Comment by MorgothNL** [comment]
Thanks for the additional comment, maybe that will clear things up better for the previous poster :)

**Comment by cryogen** [comment]
#261 fixed this
