### ISSUE TITLE
Reaping with Omnipus does not get +X amber

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2464]
My opponent had 3 tentaclid, and reaped with Omnipus, and gain only 1 instead of 4

![image](https://user-images.githubusercontent.com/57572496/115114615-9b078380-9f90-11eb-988c-e87fe814f88e.png)
![image](https://user-images.githubusercontent.com/57572496/115114536-35b39280-9f90-11eb-86e3-54e7a029d8d2.png)

**Comment by SkyJedi** [comment]
Dupe #2428

**Comment by Osarek** [comment]
Hi @SkyJedi are you sure it's a dupe?
because #2428 talks about play effect not reap effect.

#2428 
`When i played Omnipus it discarded 16 cards instead of 8 and didn't played any tentacled discarded in this way. Also the play effect of witch of the dawn doesn't apply. Anyway thank you for all your work :)`

**Comment by romanogit** [comment]
it is also fixed by the PR

**Comment by SkyJedi** [comment]
It's a dupe and the fix for it is already coded and awaiting merging

**Comment by Osarek** [comment]
ok , i've just look the PR, and saw the correction.
Thanks

**Comment by bionacid** [comment]
I tried to reap with Omnipus and Static Charge applied to the creature, i got the error 
bionacid uses Omnipus to lose [object Object],[object Object] Æmber TAG

![Cattura101](https://user-images.githubusercontent.com/82781808/115161930-a77b0180-a0a0-11eb-874c-efa8f9184912.PNG)


After that all the game was unstable... no amber from reap or other effects.

bionacid brings “Funky”, Assassina di Volpelieta to The Crucible
TAG brings Steele, Saggia Fantastica to The Crucible
TAG won the flip and is first player
 TAG has connected to the game server
 bionacid has connected to the game server
bionacid
Ciao TAG
bionacid
GL
bionacid is shuffling their deck
bionacid draws 6 card  s to their maximum of 6
TAG is shuffling their deck
TAG draws 6 card  s to their maximum of 6
TAG draws 1 card 
TAG
gl
Key phase - TAG
TAG does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TAG
bionacid
4 pour-tal :-D
TAG chooses logos  as their active house this turn
Main phase - TAG
TAG plays Mechabuoy
TAG gains an Æmber  due to Mechabuoy's bonus icon
Ready phase - TAG
TAG readies all of their cards 
Draw phase - TAG
End of turn 1
bionacid: 0 Æmber  (0 keys) TAG: 1 Æmber  (0 keys)
TURN 1 - bionacid
Key phase - bionacid
bionacid does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid
ops 3
bionacid chooses saurian  as their active house this turn
Main phase - bionacid
bionacid plays Undagnathus
bionacid plays Lapisaurus
bionacid captures an Æmber  on Undagnathus due to Lapisaurus's bonus icon
bionacid plays Undagnathus
bionacid plays Magistra Vita
Ready phase - bionacid
bionacid readies all of their cards 
Draw phase - bionacid
bionacid draws 4 card  s to their maximum of 6
End of turn 1
bionacid: 0 Æmber  (0 keys) TAG: 0 Æmber  (0 keys)
TURN 2 - TAG
Key phase - TAG
TAG does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TAG
TAG chooses sanctum  as their active house this turn
Main phase - TAG
TAG plays Sir Bevor
TAG draws a card  due to Sir Bevor's bonus icon
TAG plays Hammer-gram
TAG draws a card  due to Hammer-gram's bonus icon
TAG uses Hammer-gram to deal 3 damage and stun Undagnathus
TAG plays Hammer-gram
TAG uses Hammer-gram to deal 3 damage and stun Magistra Vita
TAG plays Orphiel, Sea's Chosen
TAG changed tide  to High
Ready phase - TAG
TAG readies all of their cards 
Draw phase - TAG
TAG draws 1 card  to their maximum of 6
TAG's chains are reduced by 1 to 2
End of turn 2
bionacid: 0 Æmber  (0 keys) TAG: 0 Æmber  (0 keys)
TURN 2 - bionacid
Key phase - bionacid
bionacid does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid chooses saurian  as their active house this turn
Main phase - bionacid
bionacid changed tide  to High
bionacid plays Venator Altum
bionacid exhausts Magistra Vita to remove its stun
bionacid exhausts Undagnathus to remove its stun
bionacid uses Lapisaurus to make Lapisaurus fight Sir Bevor
bionacid uses Undagnathus to make Undagnathus fight Sir Bevor
Ready phase - bionacid
bionacid readies all of their cards 
Draw phase - bionacid
bionacid's chains are reduced by 1 to 2
End of turn 2
bionacid: 0 Æmber  (0 keys) TAG: 0 Æmber  (0 keys)
TURN 3 - TAG
Key phase - TAG
TAG does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TAG
TAG chooses logos  as their active house this turn
Main phase - TAG
TAG plays Infomorph
TAG plays Brain Eater
TAG changed tide  to High
Ready phase - TAG
TAG readies all of their cards 
Draw phase - TAG
TAG draws 2 card  s to their maximum of 6
TAG's chains are reduced by 1 to 4
End of turn 3
bionacid: 0 Æmber  (0 keys) TAG: 0 Æmber  (0 keys)
TURN 3 - bionacid
Key phase - bionacid
bionacid does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid chooses saurian  as their active house this turn
Main phase - bionacid
bionacid uses Venator Altum to reap with Venator Altum
bionacid uses Undagnathus to reap with Undagnathus
bionacid uses Lapisaurus to reap with Lapisaurus
bionacid uses Undagnathus to reap with Undagnathus
bionacid uses Magistra Vita to reap with Magistra Vita
Ready phase - bionacid
bionacid readies all of their cards 
Draw phase - bionacid
bionacid's chains are reduced by 1 to 1
End of turn 3
bionacid: 5 Æmber  (0 keys) TAG: 0 Æmber  (0 keys)
TURN 4 - TAG
TAG uses Mechabuoy to gain 1 Æmber 
Key phase - TAG
TAG does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - TAG
TAG chooses unfathomable  as their active house this turn
Main phase - TAG
TAG plays Pour-tal
TAG gains an Æmber  due to Pour-tal's bonus icon
TAG uses Pour-tal to archive itself
TAG plays Pour-tal
TAG gains an Æmber  due to Pour-tal's bonus icon
TAG uses Pour-tal to archive itself
TAG plays Sparkfist
Ready phase - TAG
TAG readies all of their cards 
Draw phase - TAG
TAG draws 3 card  s to their maximum of 6
TAG's chains are reduced by 1 to 3
End of turn 4
bionacid: 5 Æmber  (0 keys) TAG: 3 Æmber  (0 keys)
TURN 4 - bionacid
Key phase - bionacid
bionacid does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid chooses unfathomable  as their active house this turn
Main phase - bionacid
bionacid plays Tentaclid
bionacid plays Omnipus
bionacid uses Omnipus to discard Giltspine Netcaster, Taxing Journey, Lærie of the Lake, Dry the River, Reach Advantage, Bull-wark, Gorm of Omm, and Heal or Harm
bionacid plays Tentaclid
Ready phase - bionacid
bionacid readies all of their cards 
Draw phase - bionacid
bionacid draws 3 card  s to their maximum of 6
bionacid's chains are reduced by 1 to 0
End of turn 4
bionacid: 5 Æmber  (0 keys) TAG: 3 Æmber  (0 keys)
TURN 5 - TAG
TAG uses Mechabuoy to gain 1 Æmber 
Key phase - TAG
TAG does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - TAG
TAG chooses logos  as their active house this turn
Main phase - TAG
TAG uses Brain Eater to make Brain Eater fight Lapisaurus
bionacid uses Lapisaurus to apply a lasting effect to Brain Eater
TAG uses Brain Eater to exalt Brain Eater
TAG uses Brain Eater to draw 1 card 
TAG draws 1 card 
TAG plays Bilgewarden
TAG uses Bilgewarden to raise tide  for bionacid
TAG changed tide  to High
TAG plays Static Charge attaching it to Omnipus
TAG gains an Æmber  due to Static Charge's bonus icon
TAG uses Infomorph to make Infomorph fight Tentaclid
Ready phase - TAG
TAG readies all of their cards 
Draw phase - TAG
TAG draws 1 card  to their maximum of 6
TAG's chains are reduced by 1 to 5
End of turn 5
bionacid: 5 Æmber  (0 keys) TAG: 5 Æmber  (0 keys)
TURN 5 - bionacid
bionacid uses Omnipus to deal 2 damage to Tentaclid and Magistra Vita
Key phase - bionacid
bionacid does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid
perfect upgrade for Omnipus :-D
bionacid chooses unfathomable  as their active house this turn
Main phase - bionacid
bionacid plays Tentaclid
bionacid uses Omnipus to reap with Omnipus
bionacid uses Omnipus to lose [object Object],[object Object] Æmber 
TAG
no parlo inglese scusa
bionacid
un buon upgrade per omnipus :-d
bionacid
:-D
bionacid uses Tentaclid to make Tentaclid fight Orphiel, Sea's Chosen
bionacid plays Storm Surge
bionacid captures an Æmber  on Undagnathus due to Storm Surge's bonus icon
bionacid uses Storm Surge to prevent opponent from readying cards  during the ready card  step of their next turn
Ready phase - bionacid
bionacid readies all of their cards 
Draw phase - bionacid
bionacid draws 3 card  s to their maximum of 6
End of turn 5
bionacid: NaN Æmber  (0 keys) TAG: 4 Æmber  (0 keys)
TURN 6 - TAG
TAG uses Mechabuoy to gain 1 Æmber 
Key phase - TAG
TAG does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - TAG
TAG chooses unfathomable  as their active house this turn
TAG moves all the cards  in their archives to their hand
Main phase - TAG
TAG plays Pour-tal
TAG gains an Æmber  due to Pour-tal's bonus icon
TAG uses Pour-tal to archive itself
TAG plays Pour-tal
TAG gains an Æmber  due to Pour-tal's bonus icon
TAG uses Pour-tal to archive itself
TAG plays Seabringer Kekoa
TAG uses Sparkfist to make Sparkfist fight Undagnathus
TAG uses Sparkfist to stun Undagnathus
Ready phase - TAG
Draw phase - TAG
TAG draws 1 card  to their maximum of 6
TAG's chains are reduced by 1 to 4
 TAG declares Check!
End of turn 6
bionacid: NaN Æmber  (0 keys) TAG: 7 Æmber  (0 keys)
TURN 6 - bionacid
bionacid uses Omnipus to deal 2 damage to Tentaclid and Undagnathus
Key phase - bionacid
bionacid does not forge a key. They have amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid
scusa sbaglio o non segna le chiavi
TAG
in che senso?
bionacid
siamo ancora a 0 chiavi ed abbiamo avuto abbastanza ambra per forgiarle in questi turni
TAG
nn ha forgiato nessuno di noi 2 fino ad ora
bionacid
invece che chiederti di forgiare ti riporta a 0
bionacid
adesso vediamo
TAG
io sono arrivato a sette ora
bionacid chooses sanctum  as their active house this turn
Main phase - bionacid
bionacid plays Gatekeeper
bionacid captures an Æmber  on Venator Altum due to Gatekeeper's bonus icon
TAG
sei sicuro? nn ci ho fatto caso
bionacid plays Radiant Truth
bionacid gains an Æmber  due to Radiant Truth's bonus icon
bionacid uses Radiant Truth to stun Bilgewarden, Brain Eater, and Infomorph
bionacid plays General Xalvador
Ready phase - bionacid
bionacid readies all of their cards 
Draw phase - bionacid
bionacid draws 3 card  s to their maximum of 6
End of turn 6
bionacid: NaN Æmber  (0 keys) TAG: 6 Æmber  (0 keys)
TURN 7 - TAG
TAG uses Mechabuoy to gain 1 Æmber 
Key phase - TAG
TAG forges the red key  , paying 6 Æmber 
House phase - TAG
TAG
mi sa ke ti sbagli ahhahaha
TAG chooses sanctum  as their active house this turn
bionacid
ok ma il gatekeeper non ha catturato
Main phase - TAG
TAG plays Strange Ordination
TAG gains an Æmber  due to Strange Ordination's bonus icon
TAG gains an Æmber  due to Strange Ordination's bonus icon
TAG gains an Æmber  due to Strange Ordination's bonus icon
TAG plays Orphion, Land's Chosen
Ready phase - TAG
TAG readies all of their cards 
Draw phase - TAG
TAG draws 2 card  s to their maximum of 6
TAG's chains are reduced by 1 to 3
End of turn 7
bionacid: NaN Æmber  (0 keys) TAG: 4 Æmber  (1 key)
TURN 7 - bionacid
bionacid uses Omnipus to deal 2 damage to General Xalvador and Undagnathus
Key phase - bionacid
bionacid does not forge a key. They have amber. The current cost is 6 Æmber 
House phase - bionacid
bionacid
azz per l'ambra di cattura okey li svista mia
bionacid chooses saurian  as their active house this turn
Main phase - bionacid
bionacid plays Di-No You Didn't!
bionacid gains an Æmber  due to Di-No You Didn't!'s bonus icon
bionacid uses Di-No You Didn't! to destroy Brain Eater
bionacid plays Reach Advantage
bionacid gains an Æmber  due to Reach Advantage's bonus icon
bionacid uses Reach Advantage to raise the tide 
bionacid exhausts Undagnathus to remove its stun
bionacid uses Undagnathus to make Undagnathus fight Sparkfist
bionacid uses Venator Altum to reap with Venator Altum
bionacid plays Medicus Lacus
TAG
ricordati ke robo boa da 1 Æmber  inizio di ogni turno in base alla marea quindi se ne ho 5 a inizio turno forgio con 6
bionacid
adesso ho fatto raccolto con venator e non mi ha dato l'ambra
TAG
boo se vuoi si rifa
bionacid
secondo me ci sono diverse cose strane, nulla concedo e vado
 bionacid concedes
 TAG has won the game
bionacid
aspetto qualche giorno che si sistemi DT su TCO
TAG
ci sono ancora tanti bug
 TAG has left the game
