### ISSUE TITLE
Little Niff played with Old paddy does not end immediatly turn [Rule Question]

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#2623]
I reap with [Old paddy](https://archonarcana.com/Ol%E2%80%99_Paddy) and discard 1 action, [Little Niff](https://archonarcana.com/Little_Niff) and [Deepwatter Gruen](https://archonarcana.com/Deepwater_Gruen)
So i play Little Niff, (which has Omega),
And then i was able to play Deepwater Gruen
Omaga ability was triggered after i play Deepwater

![image](https://user-images.githubusercontent.com/57572496/118946982-2f318580-b957-11eb-8a3b-70c488af25ed.png)

**Comment by romanogit** [comment]
Marked it with Rules Question:
![image](https://user-images.githubusercontent.com/2104075/118996269-26907d80-b95e-11eb-9585-bd32439898bc.png)

Can I continue the pending resolution by playing cards that cannot be played? 

Also affects [SLRS Austeralis](https://archonarcana.com/SLRS_Austeralis)

**Comment by blinkingline** [comment]
When resolving the **Reap:** ability of [Ol' Paddy](https://archonarcana.com/Ol%E2%80%99_Paddy), the playing of the cards are all considered pending effects, so each of the cards can be played. 

Once the resolution of the **Reap:** ability completes, the step will end due to [Omega](https://archonarcana.com/Omega).

**Comment by romanogit** [comment]
Not an issue
