### ISSUE TITLE
Dr Verotker and Reap or Sow

### ISSUE THREAD

**Issue by Bantha2** [keyteki/keyteki#2706]
When reaping with Dr Verotker, with the upgrade Reckless Experiment attached, you can choose to play an action or upgrade card from your discard pile.

When I do this with Dr Verotker and use Reap or Sow to ready and reap with Dr Verotker once more, after reaping, his ability once again allows the play of an action or upgrade card from the discard pile, however reap or sow has not returned to the discard pile to be played once more. This prevents me from playing it again up to rule of 6.

Thanks very much, we appreciate your work!

**Comment by jakelea99** [comment]
It is just rule issue. 

When you play 'Reap or Sow' as for reaping of Dr. Verokter, RoS doesn't return to discard pile until RoS's effect(=reaping of Dr.V) is finished.
So, it makes sense that you cannot play RoS again.

**Comment by Bantha2** [comment]
Hi fair enough, although my deck has two copies of reap or sow. If they are both in my discard pile, I should be able to reap with verotker using copy one, then reap with verotker using copy two (TCO let’s me do this), but then after reaping with both copies, neither copy have returned to discard pile. Surely after using copy number 2, copy number 1 should be back in my discard pile?

cheers 👍🏻

**Comment by jakelea99** [comment]
I think that first RoS's effect doesn't finish when second RoS is playing, so first RoS doesn't go discard pile on that timing, right?

**Comment by Bantha2** [comment]
Tbf - I’m not a judge so I wouldn’t argue with one of those. I’ve had a look at the rules. I agree with you. The first reap or sow definitely doesn’t enter the discard until the reap effect of Verotker has ended. I would argue that the moment verotker plays a second card from discard, then the first reap or sow that caused verotker to reap for the second time goes to discard. If this isn’t the case, you’d need a secondary discard pile to put all the verotker action cards until you’ve finished with him 😂🤣.

For me, verotker reap. Verotker play RoS. RoS makes Verotker reap. Verotker plays another action card from discard pile - a second RoS. I think this is the stage the first hits the discard and the second is in play. Reap with Verotker, choose an action card, then put second RoS in discard. My case to a judge would be as soon as you’ve played a second action card, the first has ended its play effect because verotker has reaped and triggered his reap ability. 

This is possibly one we’d need FFG to FAQ on though!

**Comment by blinkingline** [comment]
No need for an FFG ruling here, as they have already clarified with the ruling from [Witch of the Eye](https://archonarcana.com/Witch_of_the_Eye) and [Inspiration](https://archonarcana.com/Inspiration) that an Action card doesn't go to the discard pile until it has completed resolving, and that resolution includes the completion of the resolution of any other abilities that become available to be resolved during the resolution of the initial ability. 

In this case, [Reap or Sow](https://archonarcana.com/Reap_or_Sow) won't be in the discard until all of the reap abilities that are available to resolve due to the playing of Reap or Sow have completely resolved. That includes both the resolution of [Reckless Experimentation](https://archonarcana.com/Reckless_Experimentation) and [Dr. Verokter](https://archonarcana.com/Dr._Verokter)

**Comment by romanogit** [comment]
close, not an issue
