### ISSUE TITLE
Mimicry - Persistence Hunting - does not trigger

### ISSUE THREAD

**Issue by MorgothNL** [keyteki/keyteki#275]
Hi,

I just used my Witch of the Eye, to return Mimicry to my hand. Then played Mimicry to copy 'Persistence Hunting' from the opponent and choose to exhaust all Shadow creatures. However, the creatures did not get exhausted. I did gain the amber for persistence hunting. 

I did the same move 3 times in a row, and it did not trigger any of those times.

**Comment by Achocholacek** [comment]
Thanks for reporting - I have condensed the mimicry issues down to one issue as the effects are universally failing in expected circumstances. See Issue #285 for notes.

**Comment by vulinhchelsea** [comment]
I just encountered this issue again, not sure why this happened. Please help to take a look

> Siegers brings [Herr “Spacehook” Dak](https://www.keyforgegame.com/deck-details/4064860a-eb21-4e9e-8be7-cbf39ff9be28) to The Crucible
vulinhchelsea brings [Baalzian the Mystical](https://www.keyforgegame.com/deck-details/a0ac056d-f05c-4f8c-9493-5327f9ec1679) to The Crucible
Siegers won the flip and is first player
 Siegers has connected to the game server
 vulinhchelsea has connected to the game server
Siegers is shuffling their deck
Siegers draws 6 card  s to their maximum of 6
vulinhchelsea is shuffling their deck
vulinhchelsea draws 6 card  s to their maximum of 6
Siegers draws 1 card 
vulinhchelsea
glhf :D
Siegers
you too! new deck for me...
Key phase - Siegers
Siegers does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Siegers
Siegers chooses sanctum  as their active house this turn
Main phase - Siegers
Siegers plays Bordan the Redeemed
Ready phase - Siegers
Siegers readies their cards 
Draw phase - Siegers
End of turn 1
Siegers: 0 Æmber  (0 keys) vulinhchelsea: 0 Æmber  (0 keys)
TURN 1 - vulinhchelsea
Key phase - vulinhchelsea
vulinhchelsea does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vulinhchelsea
vulinhchelsea chooses untamed  as their active house this turn
Main phase - vulinhchelsea
vulinhchelsea plays Murmook
vulinhchelsea plays Witch of the Eye
vulinhchelsea plays Witch of the Eye
vulinhchelsea plays Nepenthe Seed
Ready phase - vulinhchelsea
vulinhchelsea readies their cards 
Draw phase - vulinhchelsea
vulinhchelsea draws 4 card  s to their maximum of 6
End of turn 1
Siegers: 0 Æmber  (0 keys) vulinhchelsea: 0 Æmber  (0 keys)
TURN 2 - Siegers
Key phase - Siegers
Siegers does not forge a key. They have 0 amber. The current cost is 7 Æmber 
House phase - Siegers
Siegers chooses brobnar  as their active house this turn
Main phase - Siegers
Siegers plays Cowfyne
Siegers plays War Grumpus
Siegers plays Cowfyne
Siegers plays Groke
Ready phase - Siegers
Siegers readies their cards 
Draw phase - Siegers
Siegers draws 4 card  s to their maximum of 6
End of turn 2
Siegers: 0 Æmber  (0 keys) vulinhchelsea: 0 Æmber  (0 keys)
TURN 2 - vulinhchelsea
Key phase - vulinhchelsea
vulinhchelsea does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - vulinhchelsea
vulinhchelsea chooses untamed  as their active house this turn
Main phase - vulinhchelsea
vulinhchelsea plays Ancient Bear
vulinhchelsea plays Cooperative Hunting
vulinhchelsea uses Cooperative Hunting to deal 1 damage to a creature for each creature they control
vulinhchelsea uses Witch of the Eye to reap with Witch of the Eye
vulinhchelsea uses Witch of the Eye to return Cooperative Hunting to their hand
vulinhchelsea plays Cooperative Hunting
vulinhchelsea uses Cooperative Hunting to deal 1 damage to a creature for each creature they control
vulinhchelsea uses Witch of the Eye to reap with Witch of the Eye
vulinhchelsea uses Witch of the Eye to return Cooperative Hunting to their hand
vulinhchelsea plays Cooperative Hunting
vulinhchelsea uses Cooperative Hunting to deal 1 damage to a creature for each creature they control
vulinhchelsea plays Nature’s Call
vulinhchelsea gains an Æmber  due to Nature’s Call's bonus icon
vulinhchelsea uses Nature’s Call to return Groke and Cowfyne to their hand
vulinhchelsea uses Murmook to reap with Murmook
Ready phase - vulinhchelsea
vulinhchelsea readies their cards 
Draw phase - vulinhchelsea
vulinhchelsea draws 3 card  s to their maximum of 6
End of turn 2
Siegers: 0 Æmber  (0 keys) vulinhchelsea: 4 Æmber  (0 keys)
TURN 3 - Siegers
Key phase - Siegers
Siegers does not forge a key. They have 0 amber. The current cost is 7 Æmber 
House phase - Siegers
Siegers chooses untamed  as their active house this turn
Main phase - Siegers
Siegers plays Persistence Hunting
Siegers gains an Æmber  due to Persistence Hunting's bonus icon
Siegers chooses house untamed 
Siegers uses Persistence Hunting to exhaust Ancient Bear, Murmook, Witch of the Eye, and Witch of the Eye
Siegers plays Inka the Spider
Siegers uses Inka the Spider to stun Ancient Bear
Siegers plays Song of Spring
Siegers gains an Æmber  due to Song of Spring's bonus icon
Siegers uses Song of Spring to return Inka the Spider to their owner's deck
Ready phase - Siegers
Draw phase - Siegers
Siegers draws 1 card  to their maximum of 6
End of turn 3
Siegers: 2 Æmber  (0 keys) vulinhchelsea: 4 Æmber  (0 keys)
TURN 3 - vulinhchelsea
Key phase - vulinhchelsea
vulinhchelsea does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - vulinhchelsea
vulinhchelsea chooses untamed  as their active house this turn
Main phase - vulinhchelsea
vulinhchelsea plays Fertility Chant
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea uses Fertility Chant to cause Siegers to gain 2 Æmber 
Ready phase - vulinhchelsea
vulinhchelsea readies their cards 
Draw phase - vulinhchelsea
vulinhchelsea draws 1 card  to their maximum of 6
 vulinhchelsea declares Check!
End of turn 3
Siegers: 4 Æmber  (0 keys) vulinhchelsea: 8 Æmber  (0 keys)
TURN 4 - Siegers
Key phase - Siegers
Siegers does not forge a key. They have 4 amber. The current cost is 7 Æmber 
House phase - Siegers
Siegers chooses brobnar  as their active house this turn
Main phase - Siegers
Siegers plays Gauntlet of Command
Siegers plays Cowfyne
Siegers plays Groke
Ready phase - Siegers
Siegers readies their cards 
Draw phase - Siegers
Siegers draws 3 card  s to their maximum of 6
End of turn 4
Siegers: 4 Æmber  (0 keys) vulinhchelsea: 8 Æmber  (0 keys)
TURN 4 - vulinhchelsea
Key phase - vulinhchelsea
vulinhchelsea forges the red key  , paying 6 Æmber 
House phase - vulinhchelsea
vulinhchelsea chooses untamed  as their active house this turn
Main phase - vulinhchelsea
vulinhchelsea exhausts Ancient Bear to remove its stun
vulinhchelsea uses Witch of the Eye to reap with Witch of the Eye
vulinhchelsea uses Witch of the Eye to return Fertility Chant to their hand
vulinhchelsea plays Fertility Chant
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea uses Fertility Chant to cause Siegers to gain 2 Æmber 
vulinhchelsea uses Witch of the Eye to reap with Witch of the Eye
vulinhchelsea uses Witch of the Eye to return Fertility Chant to their hand
vulinhchelsea plays Fertility Chant
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea gains an Æmber  due to Fertility Chant's bonus icon
vulinhchelsea uses Fertility Chant to cause Siegers to gain 2 Æmber 
vulinhchelsea uses Mimicry to to copy Persistence Hunting
vulinhchelsea plays Mimicry
vulinhchelsea gains an Æmber  due to Mimicry's bonus icon
vulinhchelsea chooses house brobnar 
vulinhchelsea uses Mimicry
vulinhchelsea uses Murmook to reap with Murmook
Ready phase - vulinhchelsea
vulinhchelsea readies their cards 
Draw phase - vulinhchelsea
vulinhchelsea draws 1 card  to their maximum of 6
 vulinhchelsea declares Check!
End of turn 4
Siegers: 8 Æmber  (0 keys) vulinhchelsea: 14 Æmber  (1 key)
TURN 5 - Siegers
Key phase - Siegers
Siegers forges the red key  , paying 7 Æmber 
House phase - Siegers
Siegers chooses brobnar  as their active house this turn
Main phase - Siegers
Siegers uses Cowfyne to make Cowfyne fight Witch of the Eye
Siegers uses Cowfyne to deal 2 damage to each neighbor of the creature being fought
Siegers uses Gauntlet of Command to ready and fight with Cowfyne
Siegers uses Cowfyne to make Cowfyne fight Murmook
Siegers uses Cowfyne to deal 2 damage to each neighbor of the creature being fought
Siegers uses Groke to make Groke fight Ancient Bear
Ready phase - Siegers
Siegers readies their cards 
Draw phase - Siegers
End of turn 5
Siegers: 1 Æmber  (1 key) vulinhchelsea: 14 Æmber  (1 key)
TURN 5 - vulinhchelsea
Key phase - vulinhchelsea
vulinhchelsea forges the blue key  , paying 6 Æmber 
House phase - vulinhchelsea
vulinhchelsea chooses sanctum  as their active house this turn
Main phase - vulinhchelsea
vulinhchelsea plays Virtuous Works
vulinhchelsea gains an Æmber  due to Virtuous Works's bonus icon
vulinhchelsea gains an Æmber  due to Virtuous Works's bonus icon
vulinhchelsea gains an Æmber  due to Virtuous Works's bonus icon
vulinhchelsea plays Champion Anaphiel
vulinhchelsea plays Bulwark
vulinhchelsea plays Shield of Justice
vulinhchelsea gains an Æmber  due to Shield of Justice's bonus icon
vulinhchelsea uses Shield of Justice to prevent their creatures from taking damage this turn
Ready phase - vulinhchelsea
vulinhchelsea readies their cards 
Draw phase - vulinhchelsea
vulinhchelsea draws 4 card  s to their maximum of 6
 vulinhchelsea declares Check!
End of turn 5
Siegers: 1 Æmber  (1 key) vulinhchelsea: 12 Æmber  (2 keys)
TURN 6 - Siegers
Key phase - Siegers
Siegers does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Siegers
vulinhchelsea
oh wait
vulinhchelsea
why your brobnar  creature is not exhauseteD?
vulinhchelsea
I mean last turn
Siegers
huh?
Siegers chooses sanctum  as their active house this turn
Main phase - Siegers
Siegers plays Gorm of Omm
vulinhchelsea
I used mimicry to copy your card 
vulinhchelsea
persistence hunting, and selected brobnar 
Siegers
huh..don't know...but you win, it doesn't matter, i guess
Siegers plays Hallowed Shield
Siegers plays Take Hostages
Siegers gains an Æmber  due to Take Hostages's bonus icon
Siegers uses Take Hostages to capture Æmber  after fighting with a creature until the end of the turn
Siegers plays Golden Aura
Siegers uses Golden Aura to heal Bulwark fully
Ready phase - Siegers
Siegers readies their cards 
Draw phase - Siegers
Siegers draws 4 card  s to their maximum of 6
End of turn 6
Siegers: 2 Æmber  (1 key) vulinhchelsea: 12 Æmber  (2 keys)
TURN 6 - vulinhchelsea
Key phase - vulinhchelsea
vulinhchelsea forges the yellow key  , paying 6 Æmber 
 vulinhchelsea has won the game
Siegers
gg
vulinhchelsea
gg
 Siegers has left the game
