### ISSUE TITLE
Double Sting

### ISSUE THREAD

**Issue by polimart** [keyteki/keyteki#2755]
Hello,

Sorry, don't have any screenshot, the game is closed.
If I have two stings and that my opponent forges a key, I receive twice the aember he used to forge.
The chat/log was something like : 

> _username1_ uses the Sting to receive 6 aember from _username2_
> _username1_ uses the Sting to receive 6 aember from _username2_

Regards

**Comment by SkyJedi** [comment]
I believe that's how it should work

https://media.discordapp.net/attachments/524218556712353827/878344515264598056/296.jpg

**Comment by blinkingline** [comment]
I think this is just bad messaging here, all the Æmber should go to the opponent, but it shouldn't double the output. 

When your opponent forges a key, one of [The Sting](https://archonarcana.com/The_Sting) resolves and that Æmber goes to the opponeent. Since there's no more Æmber that was spent to forge keys, the second copy of The Sting does nothing.

**Comment by mcarulli** [comment]
This is still giving double -- is that correct? I don't have the log either but I had 8 aember with 2x the sting, opponent forged for 6 and I had 20. Was this supposed to be fixed from romano's commit?
