### ISSUE TITLE
Remember revealed cards

### ISSUE THREAD

**Issue by Kaiserchen** [keyteki/keyteki#2788]
Some effects allow you to see the opponents hand. 

We could remember what cards are known in the opponents hand and make them visible (hover hand size?).

**Comment by blinkingline** [comment]
When cards get revealed, a list of revealed cards shows up in the game log. 
Since the hand is considered hidden information, there shouldn't be any persistent visual clues in the hand regarding the revealed cards, as other effects (e.g. archiving) could change the hand composition and giving away information about the whereabouts of a revealed card that should not be public information.
