### ISSUE TITLE
I cannot choose the order of abilities - Dhrxgar + Blast Shielding & Universal Translator

### ISSUE THREAD

**Issue by Jappe62** [keyteki/keyteki#2804]
I have a Commander Dhrxgar with Blast Shielding & Universal Translator.
And "Prompt to order simultaneous abilities" is selected from TCO settings.
I should be able to move the Blast Shielding to Dhrxgars neighbour after reaping, and then trigger Universal Translator to use the neighbouring creature and after that, move the Blast Shielding back to Commander Dhrxgar.

But right now on TCO I do not get a prompt to choose the order of abilities, Universal Translator always triggers first. Both abilities (Blast Shielding and Universal Translator) should trigger in the same timing window.

<img width="247" alt="image" src="https://user-images.githubusercontent.com/32538078/153005920-e484150e-2a41-4ad0-8dc0-1a1f839c5292.png">

**Comment by romanogit** [comment]
This issue is very tricky because it mixes the concept of "gained" ability with the source of the ability. The source of the Universtal Translator ability is Dhrxgar because UT says "this creature gains...", while Blast Shielding source is itself because it says "After this creature is used", so, in terms of engine, there were two sources, so I found the bug that the engine was considering the events to be simultaneous, but with different sources. The fact that the second source was an upgrade was crucial because the engine does not consider upgrades to be in play.
