### ISSUE TITLE
Destructive Analysis doesn't allow you to purge opponent's cards from your Archive

### ISSUE THREAD

**Issue by marc-jones** [keyteki/keyteki#307]
The 'choose cards' prompt is displayed, but you can't select your opponent's cards which are in your Archives.

Unfortunately I closed my game before taking screenshots and copying the chat log, but I think this is quite a reproducible bug, as I've had it happen in two separate games.

**Comment by skrohmagnon** [comment]
you can't purge opponent card in your archive. If they leave your archive, they goes back to your opponent hand so they are not purged and you deal no more damage.

**Comment by Achocholacek** [comment]
@skrohmagnon - yes there's a UI issue that makes opponents cards in your archives unselectable - that's what was meant. It's not actually specifically about Destructive Analysis as much as it is an engine thing ;)

**Comment by romanogit** [comment]
A few things I noticed here.

First, the game message does not log the extra damage:
romano1 plays Destructive Analysis, gaining 1 Æmber
romano1 uses Destructive Analysis to deal 2 damage to Tentacus
(nothing extra after I purged my archive cards)

Second, with #424, it is now possible to select opponent's card in the archive. There is a small glitch I just noticed. Compared to game archive popup, the archive popup for card selection is not highlighting opponent's card - compare picture bellow):

Regular Archive popup (if you click during game play):
![image](https://user-images.githubusercontent.com/2104075/64666921-56b81700-d42e-11e9-945b-85abc381f497.png)

Archive popup to select a card:
![image](https://user-images.githubusercontent.com/2104075/64666957-78b19980-d42e-11e9-9c49-7ab4b2bf95ca.png)

I then selected two cards, one mine and one from opponent. It should not kill Tentacus - and it does not:
![image](https://user-images.githubusercontent.com/2104075/64667014-a0a0fd00-d42e-11e9-990e-b62bdbe63d4f.png)

The question though is: should the player be allowed to select opponent's card since they are not "purgeable"?

**Comment by romanogit** [comment]
I was able to fix this one. Archive is now showing controlled cards:

Controlled, non-selectable, non-selected
![image](https://user-images.githubusercontent.com/2104075/65326678-6b13b680-db88-11e9-846f-cf12dbc11d09.png)

Controlled, selectable selected and selectable not-selected:
![image](https://user-images.githubusercontent.com/2104075/65326870-d52c5b80-db88-11e9-8261-2b6b10bd6907.png)

I added a padding of 4px to both discard and archive piles to count for selected border, otherwise, the border would be clipped on the left side.

This effect is also visible in the gameboard, for example, on a Nature's call being used to select a creature controlled by Collar of Subordination:
![image](https://user-images.githubusercontent.com/2104075/65327084-5e439280-db89-11e9-98c2-ef2f082cdd0a.png)

**Comment by romanogit** [comment]
Controlled box is now a more yellow:
![image](https://user-images.githubusercontent.com/2104075/65328166-0fe3c300-db8c-11e9-9cf5-6345f21b0094.png)
