### ISSUE TITLE
WoE: token UI changes

### ISSUE THREAD

**Issue by alifeee** [keyteki/keyteki#3231]
Changes

- [x] Make opponent's (own) token creature visible, so you can hover and see abilities (in tide area?)
- [x] Change 'flipped' cards to show the card back, so that tokens do not show the current card.
- [x] on hover (of flipped card), show
  - [x] if your card, what card it is (the 'underneath')
  - [x] if opponent's card, show token card zoom
- [x] Fix deck list image, when hovering on WoE decklist in-game
- [x] Exhausted enemy token creatures are seen as ready
- [x] Items invisible on tokens
  - [x] You can't see upgrades on enemy tokens (but you can on friendly tokens).
  - [x] You can't see captured amber or damage on enemy tokens (but you can on friendly tokens).
  - [x] You can't see creature power on enemy tokens (but you can on friendly tokens).
- [x] You still see friendly tokens as the underneath card -- would be nice to see them as the token card, as otherwise it gets very confusing.
- [x] You see enemy creatures as the card back -- would be nice to see them as the token card.

**Comment by strib** [comment]
I think ideally the flipped card would show the actual token creature itself, not the card back.  (Otherwise things like power modifiers would look pretty weird.)  But maybe it would be nice to have a different color border around it so it's easy to see visually how many tokens you have at a glance.

**Comment by alifeee** [comment]
decklist

![image](https://github.com/keyteki/keyteki/assets/13833017/d1b560e9-3a8f-4c43-bfa1-c4b9473488d1)

**Comment by alifeee** [comment]
>  But maybe it would be nice to have a different color border around it so it's easy to see visually how many tokens you have at a glance.

Just like the border around creatures which you took control of from your opponent

**Comment by strib** [comment]
> Currently when the token is made, it shows you the card face and asks you to put it on a flank. [According to the rules (p 33)](https://keyforging.com/wp-content/uploads/2023/04/KeyForge_Rulebook_v17_18Apr2023.pdf), you cannot look at the card face until you have already placed it in your battline:
> 
> > When I make one or more token creatures, can I look at both
> > sides of each card before I place it in my battleline?
> > > No. The card is not a token a creature until it is in play in your
> > > battleline. Only then can you look at the reverse side of the card.

FYI @dmikalova we already have a ticket for this one: #3079

**Comment by strib** [comment]
@cryogen We played a few games on dev and there are some issues with tokens still:
* Exhausted enemy tokens are always seen as ready.
* You can't see upgrades on enemy tokens (but you can on friendly tokens).
* You can't see captured amber or damage on enemy tokens (but you can on friendly tokens).
* You can see creature power on enemy tokens (but you can on friendly tokens).
* You still see friendly tokens as the underneath card -- would be nice to see them as the token card, as otherwise it gets very confusing.
* You see enemy creatures as the card back -- would be nice to see them as the token card.

Your screenshot in chat looked like you could see the token card though, so maybe the wrong thing was deployed?  Not sure.

**Comment by romanogit** [comment]
My idea for rendering tokens as to simply replace the image before sending it client side, like we do for gigantics.

**Comment by alifeee** [comment]
> We played a few games on dev and there are some issues with tokens still:

I have updated the to-do list. Some of them may be "optional" (opinionated) changes

**Comment by awmountain52** [comment]
Decklist not displaying the Unfathomable house.
![unfathomable not displaying on deck hover](https://github.com/keyteki/keyteki/assets/47752319/e8d6c921-0c58-4f9a-9bdc-d2a703c7e412)

**Comment by cryogen** [comment]
Hmm can't reproduce, that deck works ok for me 
![image](https://github.com/keyteki/keyteki/assets/1053365/ec1252a3-b2f1-4788-ab52-6bcb09235384)

**Comment by romanogit** [comment]
Let's reopen with specific issues if they happen again
