### ISSUE TITLE
WoE: raider reports "apply a lasting effect" when playing creatures or upgrades

### ISSUE THREAD

**Issue by dmikalova** [keyteki/keyteki#3239]
In a test game, whenever a creature or upgrade was played every single raider would report that it had a lasting effect applied. This is also reported for each raider at the beginning of the turn. I would expect that it would only report at the beginning of the turn.

![image](https://github.com/keyteki/keyteki/assets/324548/1de185bc-5241-451b-a917-88e5cb3f8d05)

**Comment by alifeee** [comment]
Caused by this code: raider causes a lasting effect on itself for each creature that enters play. Looks like we need another equality here like `card === self`, as this part of the code is designed to add the lasting effect when the Raider itself enters play.

https://github.com/keyteki/keyteki/blob/fd02e08091a52d21adaa0927b94bc12c810daef4/server/game/cards/06-WoE/Raider.js#L16-L24

**Comment by romanogit** [comment]
I changed Raider code
