### ISSUE TITLE
WOE: Upside down card Enhancment are showed on token 

### ISSUE THREAD

**Issue by Osarek** [keyteki/keyteki#3288]
I have created a token, the card used is maelstorm with 2 capture pips, so a blorb is created, but they is the 2 capture pips on the blorb

![image](https://github.com/keyteki/keyteki/assets/57572496/241ada36-2e92-4c1c-ac64-3c4d291a46cf)

**Comment by xoque** [comment]
I also had this issue. 
Screenshot:
<img width="920" alt="image" src="https://github.com/keyteki/keyteki/assets/19242747/f4f94612-3a35-4457-b2d7-0f463eb490d1">

Log:
XoquE brings Bailiff Hendry to The Crucible
blackholeX brings Ruffled “Livewire” Vigstein to The Crucible
blackholeX won the flip and is first player
 blackholeX has connected to the game server
 XoquE has connected to the game server
XoquE is shuffling their deck
XoquE draws 6 card  s to their maximum of 6
blackholeX is shuffling their deck
blackholeX draws 6 card  s to their maximum of 6
blackholeX draws 1 card 
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Suspended Animation
Ready phase - blackholeX
Draw phase - blackholeX
blackholeX draws 1 card  to their maximum of 6
End of turn 1
XoquE: 0 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 1 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses saurian  as their active house this turn
Main phase - XoquE
 XoquE is attempting to switch manual mode on
 blackholeX allows enabling manual mode
 XoquE switches manual mode on
 XoquE manually changed their active house to staralliance 
 XoquE switches manual mode off
XoquE plays Scout Chief Korijir
XoquE uses Scout Chief Korijir to make a token creature
XoquE plays FOF Transponder attaching it to Warrior
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 2 card  s to their maximum of 6
End of turn 1
XoquE: 0 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 2 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Yxlix Mesmerist
blackholeX plays Glylyx Weaponsmith
blackholeX plays Ironyx Rebel
blackholeX uses Ironyx Rebel to ready Yxlix Mesmerist and Glylyx Weaponsmith
blackholeX uses Yxlix Mesmerist to make Yxlix Mesmerist fight Scout Chief Korijir
blackholeX uses Glylyx Weaponsmith to make Glylyx Weaponsmith fight Warrior
XoquE uses Warrior to make a token creature
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
End of turn 2
XoquE: 0 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 2 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses saurian  as their active house this turn
Main phase - XoquE
XoquE plays Phalanx Strike
XoquE gains an Æmber  due to Phalanx Strike's bonus icon
XoquE deals 1 damage to Ironyx Rebel due to Phalanx Strike's bonus icon
XoquE uses Phalanx Strike to deal 1 damage to Ironyx Rebel
XoquE exalts Warrior to repeat Phalanx Strike's effect
XoquE uses Phalanx Strike to deal 1 damage to Yxlix Mesmerist
XoquE plays Recruit
XoquE uses Recruit to make a token creature and archive Recruit
XoquE plays Recruit
XoquE uses Recruit to make a token creature and archive Recruit
XoquE plays Phalanx Strike
XoquE gains an Æmber  due to Phalanx Strike's bonus icon
XoquE uses Phalanx Strike to deal 3 damage to Yxlix Mesmerist
XoquE exalts Warrior to repeat Phalanx Strike's effect
XoquE uses Phalanx Strike to deal 3 damage to Glylyx Weaponsmith
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 4 card  s to their maximum of 6
End of turn 2
XoquE: 2 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 3 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
 blackholeX is attempting to switch manual mode on
 XoquE allows enabling manual mode
 blackholeX switches manual mode on
 blackholeX manually changed their active house to ekwidon 
 blackholeX switches manual mode off
blackholeX plays Pull Up Stakes
blackholeX gains an Æmber  due to Pull Up Stakes's bonus icon
blackholeX uses Pull Up Stakes
blackholeX plays Mass Buyout
blackholeX uses Mass Buyout
Ready phase - blackholeX
Draw phase - blackholeX
blackholeX draws 2 card  s to their maximum of 6
End of turn 3
XoquE: 2 Æmber  (0 keys) blackholeX: 3 Æmber  (0 keys)
TURN 3 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE plays Might Club
XoquE plays Guji Dinosaur Hunter
XoquE plays Press Gang
XoquE uses Press Gang to make a token creature
XoquE plays Ragnarok Prep
XoquE captures an Æmber  on Guji Dinosaur Hunter due to Ragnarok Prep's bonus icon
XoquE deals 1 damage to Warrior due to Ragnarok Prep's bonus icon
XoquE uses Ragnarok Prep to make a token creature
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 1 card  to their maximum of 6
End of turn 3
XoquE: 2 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 4 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
blackholeX plays Crogg the Clumsy
blackholeX plays Shock Herder
blackholeX deals 1 damage to Warrior due to Shock Herder's bonus icon
blackholeX uses Shock Herder to ready and fight with a neighboring creature
blackholeX uses Crogg the Clumsy to make Crogg the Clumsy fight Warrior
blackholeX plays Barehanded
blackholeX gains an Æmber  due to Barehanded's bonus icon
blackholeX draws a card  due to Barehanded's bonus icon
blackholeX uses Barehanded to return Might Club to the top of their owner's deck
blackholeX plays Feats of Strength
blackholeX gains an Æmber  due to Feats of Strength's bonus icon
blackholeX uses Feats of Strength to make a token creature each time an enemy creature is destroyed in a fight for the remainder of the turn
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
End of turn 4
XoquE: 2 Æmber  (0 keys) blackholeX: 2 Æmber  (0 keys)
TURN 4 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses staralliance  as their active house this turn
Main phase - XoquE
XoquE plays Red Alert
XoquE uses Red Alert to deal 1 damage to Shock Herder and Crogg the Clumsy
XoquE plays Friendly Guide
XoquE deals 1 damage to Crogg the Clumsy due to Friendly Guide's bonus icon
XoquE plays Selective Preservation
XoquE uses Selective Preservation to select creatures for each power to not destroy
XoquE plays Teamwork
XoquE uses Teamwork to make a token creature
XoquE plays Recorded History
XoquE gains an Æmber  due to Recorded History's bonus icon
XoquE uses Recorded History to archive a card 
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 6 card  s to their maximum of 6
End of turn 4
XoquE: 3 Æmber  (0 keys) blackholeX: 2 Æmber  (0 keys)
TURN 5 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
blackholeX plays Hebe the Huge
blackholeX uses Hebe the Huge to deal 2 damage to each undamaged creature
blackholeX uses Crogg the Clumsy to make Crogg the Clumsy fight Friendly Guide
 blackholeX is attempting to switch manual mode on
 XoquE allows enabling manual mode
 blackholeX switches manual mode on
 blackholeX manually moves Hebe the Huge from their play area to their hand
 blackholeX removes a damage from Guji Dinosaur Hunter
 blackholeX removes a damage from Guji Dinosaur Hunter
 blackholeX removes a damage from Friendly Guide
 blackholeX removes a damage from Friendly Guide
 blackholeX removes a damage from Warrior
 blackholeX removes a damage from Warrior
 blackholeX manually changed their active house to ekwidon 
 blackholeX manually changed their active house to mars 
 blackholeX switches manual mode off
blackholeX plays Kaboom!
blackholeX deals 1 damage to Crogg the Clumsy due to Kaboom!'s bonus icon
blackholeX uses Kaboom! to Put each Mars  creature into its owner's archives, destroy each creature, and gain 3 chains.
blackholeX plays Ironyx Rebel
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 1 card  to their maximum of 6
blackholeX's chains are reduced by 1 to 2
End of turn 5
XoquE: 3 Æmber  (0 keys) blackholeX: 3 Æmber  (0 keys)
TURN 5 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses saurian  as their active house this turn
XoquE moves all the cards  in their archives to their hand
Main phase - XoquE
XoquE plays Longusaur Lector
XoquE uses Longusaur Lector to exalt Longusaur Lector
XoquE uses Longusaur Lector to make a token creature
XoquE plays Grammaticus Thrax
XoquE plays Faust the Great
XoquE plays Recruit
XoquE uses Recruit to make a token creature and archive Recruit
XoquE plays Recruit
XoquE uses Recruit to make a token creature and archive Recruit
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 2 card  s to their maximum of 6
End of turn 5
XoquE: 3 Æmber  (0 keys) blackholeX: 3 Æmber  (0 keys)
TURN 6 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 3 amber. The current cost is 7 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
blackholeX plays Hebe the Huge
blackholeX uses Hebe the Huge to deal 2 damage to each undamaged creature
blackholeX plays Smith
blackholeX gains an Æmber  due to Smith's bonus icon
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 2 card  s to their maximum of 6
blackholeX's chains are reduced by 1 to 1
End of turn 6
XoquE: 3 Æmber  (0 keys) blackholeX: 4 Æmber  (0 keys)
TURN 6 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE uses Warrior to make Warrior fight Hebe the Huge
XoquE plays Berserker Slam
XoquE gains an Æmber  due to Berserker Slam's bonus icon
XoquE uses Berserker Slam to deal 4 damage to Hebe the Huge
XoquE uses Berserker Slam to cause blackholeX to lose 1 Æmber 
XoquE plays Press Gang
XoquE uses Press Gang to make a token creature and archive Press Gang
XoquE plays Bumpsy
XoquE uses Bumpsy to make blackholeX lose 1 Æmber 
XoquE plays Crim Torchtooth
XoquE uses Warrior to reap with Warrior
XoquE uses Warrior to reap with Warrior
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 4 card  s to their maximum of 6
 XoquE declares Check!
End of turn 6
XoquE: 6 Æmber  (0 keys) blackholeX: 2 Æmber  (0 keys)
TURN 7 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 2 amber. The current cost is 7 Æmber 
House phase - blackholeX
blackholeX chooses ekwidon  as their active house this turn
Main phase - blackholeX
blackholeX plays Market Crash
blackholeX uses Market Crash to destroy each non-token creature
blackholeX plays Corner the Market
 blackholeX uses Corner the Market to stop XoquE from playing cards  next turn; when they discard a card, they may archive it instead
blackholeX plays Trade Secrets
blackholeX uses Trade Secrets to discard Exchange Program
blackholeX plays The Old Tinker
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 5 card  s to their maximum of 6
blackholeX's chains are reduced by 1 to 2
End of turn 7
XoquE: 5 Æmber  (0 keys) blackholeX: 4 Æmber  (0 keys)
TURN 7 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE discards Jarl Svend
blackholeX uses Corner the Market to allow archival of Jarl Svend instead of discard
XoquE uses Warrior to make Warrior fight The Old Tinker
XoquE uses Warrior to make Warrior fight The Old Tinker
XoquE uses Warrior to reap with Warrior
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 1 card  to their maximum of 6
 XoquE declares Check!
End of turn 7
XoquE: 6 Æmber  (0 keys) blackholeX: 4 Æmber  (0 keys)
TURN 8 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Ammonia Clouds
blackholeX uses Ammonia Clouds to deal 3 damage to all creatures
blackholeX plays Ammonia Clouds
blackholeX uses Ammonia Clouds to deal 3 damage to all creatures
Ready phase - blackholeX
Draw phase - blackholeX
blackholeX draws 2 card  s to their maximum of 6
blackholeX's chains are reduced by 1 to 1
End of turn 8
XoquE: 6 Æmber  (0 keys) blackholeX: 4 Æmber  (0 keys)
TURN 8 - XoquE
Key phase - XoquE
XoquE forges the red key  , paying 6 Æmber 
House phase - XoquE
XoquE chooses staralliance  as their active house this turn
Main phase - XoquE
XoquE plays Recorded History
XoquE gains an Æmber  due to Recorded History's bonus icon
XoquE uses Recorded History to archive 2 cards 
XoquE plays Nurse Soto
XoquE plays CXO Taber
XoquE captures an Æmber  on Nurse Soto due to CXO Taber's bonus icon
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 5 card  s to their maximum of 6
XoquE's deck has run out of cards, so they shuffle
End of turn 8
XoquE: 1 Æmber  (1 key) blackholeX: 3 Æmber  (0 keys)
TURN 9 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
blackholeX plays Stratosmack
blackholeX uses Stratosmack to deal 3 damage to Nurse Soto
blackholeX plays Jarl Svend
blackholeX plays Fresh Marks
blackholeX gains an Æmber  due to Fresh Marks's bonus icon
blackholeX uses Fresh Marks to destroy Diplomat
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
blackholeX's chains are reduced by 1 to 0
End of turn 9
XoquE: 1 Æmber  (1 key) blackholeX: 5 Æmber  (0 keys)
TURN 9 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses saurian  as their active house this turn
XoquE moves all the cards  in their archives to their hand
Main phase - XoquE
XoquE plays Æmbrosia Outpost
XoquE gains an Æmber  due to Æmbrosia Outpost's bonus icon
XoquE plays Conscription
XoquE gains an Æmber  due to Conscription's bonus icon
XoquE plays Orator Hissaro
XoquE uses Orator Hissaro to ready and exalt its neighbors
XoquE uses CXO Taber to reap with CXO Taber
XoquE uses CXO Taber to allow them to play or use one non staralliance  card  this turn
XoquE plays Recruit
XoquE uses Recruit to make a token creature and archive Recruit
XoquE plays Recruit
XoquE uses Recruit to make a token creature and archive Recruit
XoquE plays Phalanx Strike
XoquE gains an Æmber  due to Phalanx Strike's bonus icon
XoquE uses Phalanx Strike to deal 4 damage to Jarl Svend
XoquE exalts Orator Hissaro to repeat Phalanx Strike's effect
XoquE uses Phalanx Strike to deal 4 damage to Jarl Svend
 XoquE is attempting to switch manual mode on
 blackholeX allows enabling manual mode
 XoquE switches manual mode on
 XoquE manually changed their active house to brobnar 
 XoquE switches manual mode off
XoquE plays Press Gang
XoquE uses Press Gang to make a token creature and archive Press Gang
 XoquE is attempting to switch manual mode on
 blackholeX allows enabling manual mode
 XoquE switches manual mode on
 XoquE manually moves Press Gang from their archives to their discard
 XoquE switches manual mode off
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 1 card  to their maximum of 6
End of turn 9
XoquE: 5 Æmber  (1 key) blackholeX: 5 Æmber  (0 keys)
TURN 10 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Ironyx Vatminder
blackholeX uses Ironyx Vatminder to make a token creature
blackholeX plays Total Recall
blackholeX gains an Æmber  due to Total Recall's bonus icon
blackholeX uses Total Recall to gain Æmber  and return all of their creatures to their hand
blackholeX plays Ironyx Vatminder
blackholeX uses Ironyx Vatminder to make a token creature
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 2 card  s to their maximum of 6
 blackholeX declares Check!
End of turn 10
XoquE: 5 Æmber  (1 key) blackholeX: 6 Æmber  (0 keys)
TURN 10 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE plays Hebe the Huge
XoquE uses Hebe the Huge to deal 2 damage to each undamaged creature
XoquE plays Jarl Svend
XoquE plays Guji Dinosaur Hunter
XoquE plays Berserker Slam
XoquE gains an Æmber  due to Berserker Slam's bonus icon
XoquE uses Berserker Slam to deal 4 damage to Ironyx Vatminder
blackholeX uses Ironyx Vatminder to make a token creature
XoquE uses Berserker Slam to cause blackholeX to lose 1 Æmber 
 XoquE is attempting to switch manual mode on
 blackholeX allows enabling manual mode
 XoquE switches manual mode on
 blackholeX manually moves Diplomat from their play area to their discard
 XoquE switches manual mode off
XoquE uses Warrior to reap with Warrior
XoquE uses Warrior to reap with Warrior
XoquE uses Warrior to reap with Warrior
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 4 card  s to their maximum of 6
 XoquE declares Check!
End of turn 10
XoquE: 9 Æmber  (1 key) blackholeX: 5 Æmber  (0 keys)
TURN 11 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Mars Needs Æmber
blackholeX gains an Æmber  due to Mars Needs Æmber's bonus icon
blackholeX uses Mars Needs Æmber to make each damaged enemy non-mars creature capture 1 Æmber  from their side
Ready phase - blackholeX
Draw phase - blackholeX
blackholeX draws 1 card  to their maximum of 6
 blackholeX declares Check!
End of turn 11
XoquE: 4 Æmber  (1 key) blackholeX: 6 Æmber  (0 keys)
TURN 11 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE plays Press Gang
XoquE uses Press Gang to make a token creature
XoquE uses Hebe the Huge to reap with Hebe the Huge
XoquE uses Warrior to reap with Warrior
XoquE uses Warrior to reap with Warrior
XoquE uses Warrior to reap with Warrior
XoquE uses Jarl Svend to reap with Jarl Svend
XoquE uses Guji Dinosaur Hunter to reap with Guji Dinosaur Hunter
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 1 card  to their maximum of 6
 XoquE declares Check!
End of turn 11
XoquE: 10 Æmber  (1 key) blackholeX: 6 Æmber  (0 keys)
TURN 12 - blackholeX
Key phase - blackholeX
blackholeX forges the red key  , paying 6 Æmber 
House phase - blackholeX
blackholeX chooses ekwidon  as their active house this turn
Main phase - blackholeX
blackholeX plays Belligerent Guard
blackholeX uses Belligerent Guard to draw 1 card 
XoquE draws 1 card 
blackholeX plays Dthoshră, Recruiter
blackholeX plays The Old Tinker
blackholeX plays Generous Offer
blackholeX uses Generous Offer to destroy Dthoshră, Recruiter
blackholeX plays The Visible Hand
blackholeX uses Belligerent Guard to make Belligerent Guard fight CXO Taber
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 5 card  s to their maximum of 6
blackholeX's deck has run out of cards, so they shuffle
End of turn 12
XoquE: 8 Æmber  (1 key) blackholeX: 5 Æmber  (1 key)
TURN 12 - XoquE
Key phase - XoquE
XoquE forges the blue key  , paying 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE uses Hebe the Huge to make Hebe the Huge fight Belligerent Guard
XoquE uses Warrior to make Warrior fight The Old Tinker
XoquE uses Warrior to make Warrior fight The Old Tinker
XoquE uses Warrior to reap with Warrior
XoquE uses Warrior to reap with Warrior
XoquE uses Jarl Svend to reap with Jarl Svend
XoquE uses Guji Dinosaur Hunter to reap with Guji Dinosaur Hunter
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
 XoquE declares Check!
End of turn 12
XoquE: 6 Æmber  (2 keys) blackholeX: 5 Æmber  (1 key)
TURN 13 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses brobnar  as their active house this turn
Main phase - blackholeX
 blackholeX is attempting to switch manual mode on
 XoquE allows enabling manual mode
 blackholeX switches manual mode on
 blackholeX manually changed their active house to ekwidon 
 blackholeX switches manual mode off
blackholeX plays The Visible Hand
blackholeX uses The Visible Hand to make 2 token creatures and reveal their hand: Pelf, Pull Up Stakes, Total Recall, Mass Buyout, and Glylyx Weaponsmith
blackholeX plays Mass Buyout
blackholeX uses Mass Buyout to destroy Warrior, Guji Dinosaur Hunter, Jarl Svend, Warrior, Warrior, Orator Hissaro, Warrior, Diplomat, and Diplomat
blackholeX uses Mass Buyout to gain 1 amber, and XoquE gains 4 Æmber 
blackholeX plays Pull Up Stakes
blackholeX gains an Æmber  due to Pull Up Stakes's bonus icon
blackholeX uses Pull Up Stakes
Ready phase - blackholeX
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
 blackholeX declares Check!
End of turn 13
XoquE: 10 Æmber  (2 keys) blackholeX: 12 Æmber  (1 key)
TURN 13 - XoquE
Key phase - XoquE
XoquE forges the yellow key  , paying 6 Æmber 
 XoquE has won the game
