### ISSUE TITLE
With Bryozoarch in play, when I play an action, the destroyed effect from Bryo happens before enhancement pips

### ISSUE THREAD

**Issue by xoque** [keyteki/keyteki#3436]
Sorry, I don't have a log or board state, but the bug is:
Your opponent has Bryozoarch out. They also have a warded creature on their left flank.
You play an action with a damage pip enhancement. You want to use the damage pip to hit the ward before the destroyed replacement effect happens from Bryozoarch on actions.
TCO however does the destroyed effect before the damage pip.
Thank you.

**Comment by not2night** [comment]
Happened in my game as well
on turn 5
opponent had 2 Bryos in play and they both got destroyed with the Krrrzzzaaap - that's another issue btw. after we repaired that manually I played another action and first it destroyed the Bryo then gave me an ae pip 

wilki brings Thanaions of the Archer’s Subway to The Crucible
tranhoaibao brings Larunarus, the Mother of Proof to The Crucible
wilki won the flip and is first player
 wilki has connected to the game server
 tranhoaibao has connected to the game server
wilki is shuffling their deck
wilki draws 6 card  s to their maximum of 6
tranhoaibao is shuffling their deck
tranhoaibao draws 6 card  s to their maximum of 6
wilki draws 1 card 
wilki
hello hello
wilki
gl & hf
tranhoaibao
u 2!
Key phase - wilki
wilki does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses logos  as their active house this turn
Main phase - wilki
wilki plays Reassembling Automaton
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 1 card  to their maximum of 6
End of turn 1
wilki: 0 Æmber  (0 keys) tranhoaibao: 0 Æmber  (0 keys)
TURN 1 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses unfathomable  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Kamalani
tranhoaibao plays Storm Surge
 tranhoaibao uses Storm Surge to prevent opponent from readying cards  during the ready card  step of their next turn
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 2 card  s to their maximum of 6
End of turn 1
wilki: 0 Æmber  (0 keys) tranhoaibao: 0 Æmber  (0 keys)
TURN 2 - wilki
Key phase - wilki
wilki does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses dis  as their active house this turn
Main phase - wilki
wilki plays Angwish
wilki draws a card  due to Angwish's bonus icon
wilki plays Malison
wilki plays Creeping Oblivion
wilki gains an Æmber  due to Creeping Oblivion's bonus icon
wilki chooses option ' Opponent's '
wilki uses Creeping Oblivion to purge Storm Surge
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 2 card  s to their maximum of 6
End of turn 2
wilki: 1 Æmber  (0 keys) tranhoaibao: 0 Æmber  (0 keys)
TURN 2 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses ekwidon  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Steward Su-Uzyanĕ
tranhoaibao plays Dthoshră, Recruiter
tranhoaibao plays Forced Retirement
tranhoaibao uses Forced Retirement to destroy Kamalani
tranhoaibao uses Kamalani to make 2 token creatures
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
End of turn 2
wilki: 1 Æmber  (0 keys) tranhoaibao: 1 Æmber  (0 keys)
TURN 3 - wilki
Key phase - wilki
wilki does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses mars  as their active house this turn
Main phase - wilki
wilki plays Tunk
wilki plays Mars First
wilki gains an Æmber  due to Mars First's bonus icon
wilki uses Mars First to ready and use Tunk
wilki uses Tunk to make Tunk fight Dthoshră, Recruiter
wilki plays Zyzzix the Many
wilki uses Tunk to heal Tunk fully
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 3 card  s to their maximum of 6
End of turn 3
wilki: 2 Æmber  (0 keys) tranhoaibao: 1 Æmber  (0 keys)
TURN 3 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses mars  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Kaboom!
tranhoaibao uses Kaboom! to Put each Mars  creature into its owner's archives, destroy each creature, and gain 3 chains.
wilki uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
tranhoaibao plays Replay Pod
tranhoaibao plays Airlock
tranhoaibao plays Key Abduction
tranhoaibao gains an Æmber  due to Key Abduction's bonus icon
tranhoaibao uses Key Abduction to return all mars  creatures to their owner's hand
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
tranhoaibao's chains are reduced by 1 to 2
End of turn 3
wilki: 2 Æmber  (0 keys) tranhoaibao: 2 Æmber  (0 keys)
TURN 4 - wilki
Key phase - wilki
wilki does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses logos  as their active house this turn
Main phase - wilki
wilki plays Thorium Plasmate
wilki gains an Æmber  due to Thorium Plasmate's bonus icon
wilki plays Ecto-Charge
wilki gains an Æmber  due to Ecto-Charge's bonus icon
wilki discards Backup Plan
tranhoaibao
wow
wilki discards Mind Bullets
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 4 card  s to their maximum of 6
End of turn 4
wilki: 4 Æmber  (0 keys) tranhoaibao: 2 Æmber  (0 keys)
TURN 4 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses unfathomable  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Bryozoarch
tranhoaibao draws a card  due to Bryozoarch's bonus icon
tranhoaibao plays Bryozoarch
tranhoaibao plays Cup of Water
tranhoaibao gains an Æmber  due to Cup of Water's bonus icon
tranhoaibao uses Cup of Water to stun Reassembling Automaton
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 2 card  s to their maximum of 6
tranhoaibao's chains are reduced by 1 to 1
End of turn 4
wilki: 4 Æmber  (0 keys) tranhoaibao: 3 Æmber  (0 keys)
TURN 5 - wilki
Key phase - wilki
wilki does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - wilki
wilki
all the wrong cards  at the wrong time
wilki chooses logos  as their active house this turn
Main phase - wilki
wilki plays Krrrzzzaaap!!!
tranhoaibao uses Bryozoarch to destroy Bryozoarch
tranhoaibao uses Bryozoarch to destroy Bryozoarch
wilki
uhm
wilki
I don't think that worked right
tranhoaibao
yeah
tranhoaibao
1 should survive
wilki
get one of them back
 wilki is attempting to switch manual mode on
 tranhoaibao allows enabling manual mode
 wilki switches manual mode on
 tranhoaibao manually moves Bryozoarch from their discard to their play area
 tranhoaibao switches manual mode off
wilki plays Thorium Plasmate
tranhoaibao uses Bryozoarch to destroy Bryozoarch
wilki gains an Æmber  due to Thorium Plasmate's bonus icon
wilki plays Opposition Research
 wilki uses Opposition Research to stop tranhoaibao from reaping next turn
wilki exhausts Reassembling Automaton to remove its stun
wilki plays Chronophage
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 4 card  s to their maximum of 6
End of turn 5
wilki: 5 Æmber  (0 keys) tranhoaibao: 3 Æmber  (0 keys)
TURN 5 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses ekwidon  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Market Crash
tranhoaibao uses Market Crash to destroy each non-token creature
wilki uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
tranhoaibao plays Molluscaller
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 2 card  s to their maximum of 6
tranhoaibao's chains are reduced by 1 to 2
End of turn 5
wilki: 5 Æmber  (0 keys) tranhoaibao: 3 Æmber  (0 keys)
TURN 6 - wilki
Key phase - wilki
wilki does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses dis  as their active house this turn
Main phase - wilki
wilki plays Dominator Bauble
wilki plays Impspector
wilki plays Shaffles
wilki plays Snudge
wilki deals 1 damage to Molluscaller due to Snudge's bonus icon
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 4 card  s to their maximum of 6
wilki uses Shaffles to make tranhoaibao lose 1 Æmber 
End of turn 6
wilki: 5 Æmber  (0 keys) tranhoaibao: 2 Æmber  (0 keys)
TURN 6 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses unfathomable  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Sparkfist
tranhoaibao plays Soleft
tranhoaibao plays Plunder
tranhoaibao gains an Æmber  due to Plunder's bonus icon
tranhoaibao uses Plunder to reveal a random unrevealed card  from wilki's hand
Plunder reveals Umbra-Bot
tranhoaibao chooses option ' Repeat this effect '
tranhoaibao uses Plunder to reveal a random unrevealed card  from wilki's hand
Plunder reveals Lethologica
tranhoaibao chooses option ' Repeat this effect '
tranhoaibao uses Plunder to reveal a random unrevealed card  from wilki's hand
Plunder reveals Destructive Analysis
tranhoaibao chooses option ' Repeat this effect '
tranhoaibao uses Plunder to reveal a random unrevealed card  from wilki's hand
Plunder reveals Gluttony
tranhoaibao chooses option ' Discard this card  '
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
tranhoaibao's chains are reduced by 1 to 1
End of turn 6
wilki: 5 Æmber  (0 keys) tranhoaibao: 3 Æmber  (0 keys)
TURN 7 - wilki
Key phase - wilki
wilki does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses dis  as their active house this turn
Main phase - wilki
wilki uses Dominator Bauble to use Reassembling Automaton
wilki uses Reassembling Automaton to make Reassembling Automaton fight Soleft
wilki uses Reassembling Automaton to heal all damage from Reassembling Automaton, exhaust it and move it to a flank
wilki uses Snudge to reap with Snudge
wilki uses Snudge to return Molluscaller to their hand
wilki uses Shaffles to reap with Shaffles
wilki uses Impspector to make Impspector fight Sparkfist
wilki uses Impspector to purge a card  at random from tranhoaibao's hand
tranhoaibao purges Steward Su-Uzyanĕ at random
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 1 card  to their maximum of 6
wilki uses Shaffles to make tranhoaibao lose 1 Æmber 
 wilki declares Check!
End of turn 7
wilki: 7 Æmber  (0 keys) tranhoaibao: 2 Æmber  (0 keys)
TURN 7 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - tranhoaibao
tranhoaibao chooses mars  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Key Abduction
tranhoaibao gains an Æmber  due to Key Abduction's bonus icon
tranhoaibao uses Key Abduction to return all mars  creatures to their owner's hand
tranhoaibao plays Scoop Up
tranhoaibao gains an Æmber  due to Scoop Up's bonus icon
tranhoaibao uses Scoop Up to archive Snudge
tranhoaibao plays Yxlix Mesmerist
tranhoaibao uses Airlock to discard Molluscaller
tranhoaibao draws 1 card 
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
tranhoaibao's chains are reduced by 1 to 0
End of turn 7
wilki: 7 Æmber  (0 keys) tranhoaibao: 4 Æmber  (0 keys)
TURN 8 - wilki
Key phase - wilki
wilki forges the red key  , paying 6 Æmber 
House phase - wilki
wilki chooses mars  as their active house this turn
wilki moves all the cards  in their archives to their hand
Main phase - wilki
wilki plays Destructive Analysis
wilki gains an Æmber  due to Destructive Analysis's bonus icon
wilki deals 1 damage to Yxlix Mesmerist due to Destructive Analysis's bonus icon
wilki uses Destructive Analysis to deal 2 damage to Yxlix Mesmerist
wilki plays Nyzyk Resonator
wilki plays Martian Hounds
wilki draws a card  due to Martian Hounds's bonus icon
wilki uses Martian Hounds to place 2 +1 power counters on Nyzyk Resonator
wilki plays Tunk
wilki plays Zyzzix the Many
wilki uses Tunk to heal Tunk fully
wilki plays Glyxl Proliferator
wilki uses Tunk to heal Tunk fully
wilki plays Space Invaders
wilki uses Space Invaders to reveal and tokenize Umbra-Bot
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 5 card  s to their maximum of 6
wilki uses Shaffles to make tranhoaibao lose 1 Æmber 
End of turn 8
wilki: 2 Æmber  (1 key) tranhoaibao: 3 Æmber  (0 keys)
TURN 8 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 3 amber. The current cost is 10 Æmber 
House phase - tranhoaibao
tranhoaibao chooses mars  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Selwyn the Fence
tranhoaibao plays Phosphorus Stars
tranhoaibao gains an Æmber  due to Phosphorus Stars's bonus icon
tranhoaibao uses Phosphorus Stars to stun each non-Mars creature and gain 2 chains
tranhoaibao uses Airlock to discard Flounderight
tranhoaibao draws 1 card 
tranhoaibao plays Storm Crawler
tranhoaibao uses Yxlix Mesmerist to make Yxlix Mesmerist fight Rebel
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
tranhoaibao's chains are reduced by 1 to 1
End of turn 8
wilki: 2 Æmber  (1 key) tranhoaibao: 4 Æmber  (0 keys)
TURN 9 - wilki
Key phase - wilki
wilki does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses mars  as their active house this turn
Main phase - wilki
wilki uses Tunk to make Tunk fight Storm Crawler
wilki uses Zyzzix the Many to make Zyzzix the Many fight Storm Crawler
tranhoaibao uses Storm Crawler to place a card  under Replay Pod
wilki uses Zyzzix the Many to reveal Overlord Greking
wilki uses Glyxl Proliferator to reap with Glyxl Proliferator
wilki uses Glyxl Proliferator to archive Martian Hounds
wilki uses Nyzyk Resonator to reap with Nyzyk Resonator
wilki plays Glylyx Weaponsmith
wilki uses Tunk to heal Tunk fully
wilki plays Memrox the Red
wilki uses Tunk to heal Tunk fully
wilki plays Scoop Up
wilki gains an Æmber  due to Scoop Up's bonus icon
wilki uses Scoop Up to archive Reassembling Automaton
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 4 card  s to their maximum of 6
wilki uses Shaffles to make tranhoaibao lose 1 Æmber 
End of turn 9
wilki: 5 Æmber  (1 key) tranhoaibao: 3 Æmber  (0 keys)
TURN 9 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 3 amber. The current cost is 10 Æmber 
House phase - tranhoaibao
tranhoaibao
that's too hard
tranhoaibao chooses ekwidon  as their active house this turn
Main phase - tranhoaibao
tranhoaibao plays Flea Market
tranhoaibao draws a card  due to Flea Market's bonus icon
tranhoaibao plays Tya-Arhĭ, Esquire
tranhoaibao gains an Æmber  due to Tya-Arhĭ, Esquire's bonus icon
tranhoaibao plays Hire On
tranhoaibao uses Hire On to make a token creature and archive Hire On
tranhoaibao plays Hire On
tranhoaibao uses Hire On to make a token creature and archive Hire On
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
tranhoaibao's deck has run out of cards, so they shuffle
tranhoaibao's chains are reduced by 1 to 0
End of turn 9
wilki: 5 Æmber  (1 key) tranhoaibao: 4 Æmber  (0 keys)
TURN 10 - wilki
Key phase - wilki
wilki does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - wilki
wilki chooses mars  as their active house this turn
Main phase - wilki
wilki uses Zyzzix the Many to make Zyzzix the Many fight Tya-Arhĭ, Esquire
tranhoaibao uses Tya-Arhĭ, Esquire to make a token creature
wilki uses Zyzzix the Many to reveal Envy
wilki uses Tunk to make Tunk fight Yxlix Mesmerist
tranhoaibao uses Yxlix Mesmerist to place a card  under Replay Pod
wilki uses Nyzyk Resonator to reap with Nyzyk Resonator
wilki uses Glylyx Weaponsmith to reap with Glylyx Weaponsmith
wilki uses Memrox the Red to reap with Memrox the Red
wilki uses Glyxl Proliferator to reap with Glyxl Proliferator
wilki uses Glyxl Proliferator to archive Scoop Up
wilki plays Grommid
wilki uses Tunk to heal Tunk fully
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 2 card  s to their maximum of 6
wilki's deck has run out of cards, so they shuffle
wilki uses Shaffles to make tranhoaibao lose 1 Æmber 
 wilki declares Check!
End of turn 10
wilki: 9 Æmber  (1 key) tranhoaibao: 3 Æmber  (0 keys)
TURN 10 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 3 amber. The current cost is 10 Æmber 
House phase - tranhoaibao
tranhoaibao chooses mars  as their active house this turn
Main phase - tranhoaibao
tranhoaibao uses Selwyn the Fence to reap with Selwyn the Fence
tranhoaibao plays Scoop Up
tranhoaibao gains an Æmber  due to Scoop Up's bonus icon
tranhoaibao uses Scoop Up to archive Strange Shell and Shaffles
tranhoaibao plays Insurance Policy attaching it to Selwyn the Fence
tranhoaibao uses Insurance Policy to make tranhoaibao lose 1 Æmber 
tranhoaibao uses Airlock to discard Steward Su-Uzyanĕ
tranhoaibao draws 1 card 
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
tranhoaibao draws 3 card  s to their maximum of 6
End of turn 10
wilki: 9 Æmber  (1 key) tranhoaibao: 4 Æmber  (0 keys)
TURN 11 - wilki
Key phase - wilki
wilki forges the blue key  , paying 6 Æmber 
House phase - wilki
wilki chooses mars  as their active house this turn
Main phase - wilki
wilki uses Grommid to make Grommid fight Strange Shell
wilki uses Grommid to make tranhoaibao lose 1 Æmber 
wilki plays Mars First
wilki gains an Æmber  due to Mars First's bonus icon
wilki uses Mars First to ready and use Grommid
wilki uses Grommid to make Grommid fight Strange Shell
wilki uses Grommid to make tranhoaibao lose 1 Æmber 
wilki uses Glyxl Proliferator to reap with Glyxl Proliferator
wilki uses Glyxl Proliferator to archive Mars First
wilki uses Zyzzix the Many to reap with Zyzzix the Many
wilki uses Zyzzix the Many to reveal Sloth
wilki uses Tunk to reap with Tunk
wilki uses Nyzyk Resonator to reap with Nyzyk Resonator
wilki uses Glylyx Weaponsmith to reap with Glylyx Weaponsmith
wilki uses Memrox the Red to reap with Memrox the Red
Ready phase - wilki
wilki readies their cards 
Draw phase - wilki
wilki draws 2 card  s to their maximum of 6
 wilki declares Check!
End of turn 11
wilki: 10 Æmber  (2 keys) tranhoaibao: 2 Æmber  (0 keys)
TURN 11 - tranhoaibao
Key phase - tranhoaibao
tranhoaibao does not forge a key. They have 2 amber. The current cost is 10 Æmber 
House phase - tranhoaibao
tranhoaibao
why don't you use Action?
tranhoaibao chooses mars  as their active house this turn
tranhoaibao moves all the cards  in their archives to their hand
Snudge leaves the archives and will be returned its owner hand
Shaffles leaves the archives and will be returned its owner hand
Main phase - tranhoaibao
tranhoaibao uses Selwyn the Fence to reap with Selwyn the Fence
tranhoaibao uses Replay Pod to return the cards  under it to hand and purge Replay Pod
tranhoaibao uses Airlock to discard Forced Retirement
tranhoaibao draws 1 card 
tranhoaibao plays Key Abduction
tranhoaibao gains an Æmber  due to Key Abduction's bonus icon
tranhoaibao uses Key Abduction to return all mars  creatures to their owner's hand
tranhoaibao forges the yellow key  , paying 4 Æmber 
tranhoaibao plays Phosphorus Stars
tranhoaibao gains an Æmber  due to Phosphorus Stars's bonus icon
tranhoaibao uses Phosphorus Stars to stun each non-Mars creature and gain 2 chains
tranhoaibao plays Selwyn the Fence
tranhoaibao plays Yxlix Mesmerist
tranhoaibao plays Storm Crawler
Ready phase - tranhoaibao
tranhoaibao readies their cards 
Draw phase - tranhoaibao
End of turn 11
wilki: 10 Æmber  (2 keys) tranhoaibao: 1 Æmber  (1 key)
TURN 12 - wilki
Key phase - wilki
wilki forges the yellow key  , paying 6 Æmber 
 wilki has won the game
wilki
what action?
tranhoaibao
gg
wilki
gg
tranhoaibao
Action of Memrox
tranhoaibao
you have 7 card  in Archive
wilki
lol
wilki
I didn't read it :blush:
wilki
thx
wilki
first time I'm playing this
tranhoaibao
haha
tranhoaibao
cya
 tranhoaibao has left the game
