### ISSUE TITLE
Scoop Up+Tourist Trap

### ISSUE THREAD

**Issue by CatMarrow** [keyteki/keyteki#3481]
If I control a creature that is owned by my opponent and I try to put it into my own archives with Scoop Up, it enters my opponent's archives instead. I have only seen this occur with Tourist Trap swapping, but it's possible it occurs with any card that transfers control of a creature.

**Comment by strib** [comment]
This is correct behavior as ruled by judges in Discord.  The problem is that Scoop Up only puts a lasting effect to go back to the opponent's hand for the opponent-controlled card.  If the opponent-owned-but-friendly creature goes into your archives, then it would go to your hand when you take your archives, which is an illegal game state.

**Comment by CatMarrow** [comment]
Wow, that is super interesting! Sorry for reporting intended behaviour
then.
