### ISSUE TITLE
Brash Grabber allowed to reap when enraged / May be Loyal Packmate bug

### ISSUE THREAD

**Issue by xoque** [keyteki/keyteki#3855]
Brash Grabber is enraged (it entered play when not haunted), and although there are opponent creatures, it allows me the option to reap.

Screenshot:
![image](https://github.com/keyteki/keyteki/assets/19242747/0d65ce0f-8a58-46cb-aa57-301970daf835)

Log up to failure:
XoquE brings Hue the Rapidly Twisted to The Crucible
blackholeX brings Owen, the Justiciar of Gostoke to The Crucible
blackholeX won the flip and is first player
 blackholeX has connected to the game server
 XoquE has connected to the game server
XoquE is shuffling their deck
XoquE draws 6 card  s to their maximum of 6
blackholeX is shuffling their deck
blackholeX draws 6 card  s to their maximum of 6
blackholeX draws 1 card 
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Dr. Xyloxxzlphrex
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
End of turn 1
XoquE: 0 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 1 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses untamed  as their active house this turn
Main phase - XoquE
XoquE plays Witch of the Eye
XoquE plays Fangtooth Cavern
XoquE gains an Æmber  due to Fangtooth Cavern's bonus icon
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 2 card  s to their maximum of 6
XoquE uses Fangtooth Cavern to destroy Dr. Xyloxxzlphrex
End of turn 1
XoquE: 1 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 2 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses untamed  as their active house this turn
Main phase - blackholeX
blackholeX plays Witch of the Spore
blackholeX discards Brash Grabber due to Witch of the Spore's bonus icon
blackholeX plays Loyal Packmate
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
End of turn 2
XoquE: 1 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 2 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses brobnar  as their active house this turn
Main phase - XoquE
XoquE plays Cannon
XoquE plays Blunderbore
XoquE plays Recklessness
XoquE gains an Æmber  due to Recklessness's bonus icon
XoquE uses Recklessness to do several things
XoquE discards Modular Exoskeleton, Stronger Together, and Com. Officer Palik at random
blackholeX discards Addlefish, Effigy of Melerukh, and Echo Guardian at random
XoquE draws 3 card  s
blackholeX draws 3 card  s
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 3 card  s to their maximum of 6
XoquE uses Fangtooth Cavern to destroy Witch of the Eye
End of turn 2
XoquE: 2 Æmber  (0 keys) blackholeX: 0 Æmber  (0 keys)
TURN 3 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Scoop Up
blackholeX gains an Æmber  due to Scoop Up's bonus icon
blackholeX uses Scoop Up to archive Witch of the Spore and Blunderbore
blackholeX plays Xyp the Implanter
blackholeX deals 1 damage to Xyp the Implanter due to Xyp the Implanter's bonus icon
blackholeX plays The Red Death
blackholeX gains an Æmber  due to The Red Death's bonus icon
 blackholeX is attempting to switch manual mode on
 XoquE allows enabling manual mode
 blackholeX switches manual mode on
 blackholeX removes a damage from Xyp the Implanter
 blackholeX switches manual mode off
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
End of turn 3
XoquE: 2 Æmber  (0 keys) blackholeX: 2 Æmber  (0 keys)
TURN 3 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses untamed  as their active house this turn
Main phase - XoquE
XoquE plays Curse of Fertility
XoquE plays Warfaline
XoquE chooses option ' Opponent's '
XoquE uses Warfaline to shuffle the top 5 cards  of a discard pile into the owner's deck
XoquE discards Spoo-key Charge
XoquE discards Came Back Wrong
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 4 card  s to their maximum of 6
XoquE uses Fangtooth Cavern to destroy Xyp the Implanter
End of turn 3
XoquE: 2 Æmber  (0 keys) blackholeX: 2 Æmber  (0 keys)
TURN 4 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses untamed  as their active house this turn
blackholeX moves all the cards  in their archives to their hand
Blunderbore leaves the archives and will be returned its owner hand
Main phase - blackholeX
blackholeX plays Cauldron
blackholeX plays Witch of the Wilds
blackholeX discards Arcane Transmitter due to Witch of the Wilds's bonus icon
blackholeX uses Arcane Transmitter to return Arcane Transmitter, Xyp the Implanter, and Dr. Xyloxxzlphrex to their owner's deck
blackholeX discards Warfaline
blackholeX plays Witch of the Spore
blackholeX discards Wrath or Ruin due to Witch of the Spore's bonus icon
blackholeX uses Loyal Packmate to reap with Loyal Packmate
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 5 card  s to their maximum of 6
End of turn 4
XoquE: 2 Æmber  (0 keys) blackholeX: 3 Æmber  (0 keys)
TURN 4 - XoquE
XoquE uses Modular Exoskeleton to return Modular Exoskeleton to their hand
Key phase - XoquE
XoquE does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses staralliance  as their active house this turn
Main phase - XoquE
XoquE plays Near-Future Lens
XoquE uses Near-Future Lens to reveal Ornar Skullface
XoquE plays Prototype Harness attaching it to Warfaline
XoquE gains an Æmber  due to Prototype Harness's bonus icon
XoquE plays Modular Exoskeleton attaching it to Warfaline
XoquE plays Perimeter Alarm
XoquE uses Perimeter Alarm to use Warfaline
XoquE uses Warfaline to make Warfaline fight Loyal Packmate
XoquE chooses option ' Opponent's '
XoquE uses Warfaline to shuffle the top 5 cards  of a discard pile into the owner's deck
XoquE discards Perimeter Alarm
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 3 card  s to their maximum of 6
XoquE uses Near-Future Lens to reveal Proton Siphon on top of their deck
XoquE uses Near-Future Lens to reveal Rorag Screamer on top of their deck
XoquE uses Near-Future Lens to reveal Lost in the Wild on top of their deck
XoquE uses Fangtooth Cavern to destroy Witch of the Wilds
End of turn 4
XoquE: 3 Æmber  (0 keys) blackholeX: 3 Æmber  (0 keys)
TURN 5 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX uses Cauldron to place Haunting Witch under Cauldron
blackholeX plays Deep Probe
blackholeX gains an Æmber  due to Deep Probe's bonus icon
blackholeX discards Blernean Hydra due to Deep Probe's bonus icon
blackholeX discards Thing from the Deep due to Deep Probe's bonus icon
blackholeX chooses house brobnar 
blackholeX uses Deep Probe to discard all brobnar  creature cards  from XoquE's hand: Headhunter, Æmber Storm, Blunderbore, Ornar Skullface, Proton Siphon, and Rorag Screamer
blackholeX plays Xyp the Implanter
blackholeX deals 1 damage to Warfaline due to Xyp the Implanter's bonus icon
blackholeX plays Target Yynxzdyl
blackholeX uses Target Yynxzdyl to archive Witch of the Wilds
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 5 card  s to their maximum of 6
End of turn 5
XoquE: 3 Æmber  (0 keys) blackholeX: 4 Æmber  (0 keys)
TURN 5 - XoquE
XoquE uses Warfaline to deal 1 damage to Warfaline
Key phase - XoquE
XoquE does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses untamed  as their active house this turn
Main phase - XoquE
XoquE uses Warfaline to reap with Warfaline
XoquE plays Æmber Storm
XoquE gains an Æmber  due to Æmber Storm's bonus icon
XoquE uses Æmber Storm to deal 1 damage to an enemy creature for each Æmber  in their pool
XoquE uses Near-Future Lens to play Lost in the Wild
XoquE plays Lost in the Wild
XoquE uses Near-Future Lens to reveal Soul Bomb on top of their deck
XoquE gains an Æmber  due to Lost in the Wild's bonus icon
XoquE uses Lost in the Wild to return Warfaline, The Red Death, and Witch of the Spore to their owner's deck
XoquE uses Near-Future Lens to reveal Bog Spitter on top of their deck
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 5 card  s to their maximum of 6
XoquE uses Near-Future Lens to reveal Reclaimed by Nature on top of their deck
XoquE uses Near-Future Lens to reveal Sensor Chief Garcia on top of their deck
XoquE uses Near-Future Lens to reveal Warfaline on top of their deck
XoquE uses Near-Future Lens to reveal Mournful Barn-Burner on top of their deck
XoquE uses Near-Future Lens to reveal Blunderbore on top of their deck
 XoquE declares Check!
End of turn 5
XoquE: 6 Æmber  (0 keys) blackholeX: 4 Æmber  (0 keys)
TURN 6 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses untamed  as their active house this turn
blackholeX moves all the cards  in their archives to their hand
Main phase - blackholeX
blackholeX plays Loyal Packmate
blackholeX plays Witch of the Wilds
blackholeX discards Abduct-o-Matic due to Witch of the Wilds's bonus icon
blackholeX uses Abduct-o-Matic to capture 2 Æmber  from their opponent , placing it on Witch of the Wilds
blackholeX plays Grave Pixie
blackholeX gains an Æmber  due to Grave Pixie's bonus icon
blackholeX uses Cauldron to place Way of the Porcupine under Cauldron
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 3 card  s to their maximum of 6
End of turn 6
XoquE: 4 Æmber  (0 keys) blackholeX: 5 Æmber  (0 keys)
TURN 6 - XoquE
Key phase - XoquE
XoquE does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses untamed  as their active house this turn
Main phase - XoquE
XoquE plays Reclaimed by Nature
XoquE gains an Æmber  due to Reclaimed by Nature's bonus icon
XoquE uses Reclaimed by Nature to purge Cauldron and resolve its bonus icons
XoquE uses Near-Future Lens to play Blunderbore
XoquE plays Blunderbore
XoquE uses Near-Future Lens to reveal Near-Future Lens on top of their deck
XoquE discards Warfaline
XoquE discards Bog Spitter
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 3 card  s to their maximum of 6
XoquE uses Near-Future Lens to reveal Reclaimed by Nature on top of their deck
XoquE uses Near-Future Lens to reveal Cauldron on top of their deck
XoquE uses Near-Future Lens to reveal Heavyweight Morik on top of their deck
XoquE uses Fangtooth Cavern to destroy Grave Pixie
End of turn 6
XoquE: 5 Æmber  (0 keys) blackholeX: 5 Æmber  (0 keys)
TURN 7 - blackholeX
Key phase - blackholeX
blackholeX does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Dr. Xyloxxzlphrex
blackholeX plays Brash Grabber
blackholeX discards Effigy of Melerukh due to Brash Grabber's bonus icon
blackholeX plays Don’t Believe Your Eyes
blackholeX uses Don’t Believe Your Eyes to capture 2 Æmber  from XoquE, placing it on Blunderbore
blackholeX plays Æmber Storm
blackholeX gains an Æmber  due to Æmber Storm's bonus icon
blackholeX discards Witch of the Spore due to Æmber Storm's bonus icon
blackholeX uses Witch of the Spore to deal 3 damage to Blunderbore
blackholeX uses Æmber Storm to deal 1 damage to an enemy creature for each Æmber  in their pool
Ready phase - blackholeX
blackholeX readies their cards 
Draw phase - blackholeX
blackholeX draws 6 card  s to their maximum of 6
 blackholeX declares Check!
End of turn 7
XoquE: 3 Æmber  (0 keys) blackholeX: 8 Æmber  (0 keys)
TURN 7 - XoquE
XoquE uses Modular Exoskeleton to return Modular Exoskeleton to their hand
Key phase - XoquE
XoquE does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - XoquE
XoquE chooses staralliance  as their active house this turn
Main phase - XoquE
XoquE plays Near-Future Lens
XoquE uses Near-Future Lens to reveal Heavyweight Morik
XoquE plays Sensor Chief Garcia
XoquE uses Sensor Chief Garcia to increase key cost by 2 during blackholeX's next turn
XoquE plays Modular Exoskeleton attaching it to Sensor Chief Garcia
XoquE plays Proton Siphon attaching it to Sensor Chief Garcia
XoquE gains an Æmber  due to Proton Siphon's bonus icon
XoquE uses Near-Future Lens to play Heavyweight Morik
XoquE plays Heavyweight Morik
XoquE uses Near-Future Lens to reveal Near-Future Lens on top of their deck
Ready phase - XoquE
XoquE readies their cards 
Draw phase - XoquE
XoquE draws 3 card  s to their maximum of 6
XoquE uses Near-Future Lens to reveal Retrotechnician Le on top of their deck
XoquE uses Near-Future Lens to reveal Soul Bomb on top of their deck
XoquE uses Near-Future Lens to reveal Soul Bomb on top of their deck
XoquE uses Fangtooth Cavern to destroy Dr. Xyloxxzlphrex
End of turn 7
XoquE: 4 Æmber  (0 keys) blackholeX: 8 Æmber  (0 keys)
TURN 8 - blackholeX
Key phase - blackholeX
blackholeX forges the red key  , paying 8 Æmber 
House phase - blackholeX
blackholeX chooses mars  as their active house this turn
Main phase - blackholeX
blackholeX plays Haunting Witch
blackholeX uses Haunting Witch to gain 1 Æmber 
blackholeX plays Target Yynxzdyl
blackholeX discards Open the Seal due to Target Yynxzdyl's bonus icon
blackholeX uses Haunting Witch to gain 1 Æmber 
blackholeX uses Target Yynxzdyl to archive Don’t Believe Your Eyes
blackholeX uses Brash Grabber to reap with Brash Grabber

**Comment by xoque** [comment]
Ah, thinking about this more it might be related to a Loyal Packmate bug - I've seen it affect enemies before. So even though I have Loyal Packmate, it thinks I can't attack enemies because they do not have taunt.

**Comment by TomGraafland** [comment]
Can confirm that loyal packmate is not functioning well at the moment.
Friendly creatures can only reap:

![image](https://github.com/keyteki/keyteki/assets/32635292/4a7f8bb3-7ce6-4541-9499-5ad884a5455b)




log:

LordJudo brings P. B. Stylobyte of the Blue Church to The Crucible
TomG_LordJudo brings Relebreaker, the Healer of Flowers to The Crucible
 LordJudo has connected to the game server
 TomG_LordJudo has connected to the game server
LordJudo chooses to randomize the first player
LordJudo won the flip and is first player
LordJudo is shuffling their deck
LordJudo draws 6 card  s to their maximum of 6
TomG_LordJudo is shuffling their deck
TomG_LordJudo draws 6 card  s to their maximum of 6
LordJudo draws 1 card 
Key phase - LordJudo
LordJudo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - LordJudo
LordJudo chooses untamed  as their active house this turn
Main phase - LordJudo
LordJudo plays Loyal Packmate
Ready phase - LordJudo
LordJudo readies their cards 
Draw phase - LordJudo
End of turn 1
LordJudo: 0 Æmber  (0 keys) TomG_LordJudo: 0 Æmber  (0 keys)
TURN 1 - TomG_LordJudo
Key phase - TomG_LordJudo
TomG_LordJudo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - TomG_LordJudo
TomG_LordJudo chooses geistoid  as their active house this turn
Main phase - TomG_LordJudo
TomG_LordJudo plays Cursed Tomb
TomG_LordJudo gains an Æmber  due to Cursed Tomb's bonus icon
TomG_LordJudo plays Boiler
TomG_LordJudo deals 1 damage to Loyal Packmate due to Boiler's bonus icon
TomG_LordJudo discards Invigorating Shower due to Boiler's bonus icon
Ready phase - TomG_LordJudo
TomG_LordJudo readies their cards 
Draw phase - TomG_LordJudo
TomG_LordJudo draws 4 card  s to their maximum of 6
End of turn 1
LordJudo: 0 Æmber  (0 keys) TomG_LordJudo: 1 Æmber  (0 keys)
TURN 2 - LordJudo
Key phase - LordJudo
LordJudo does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - LordJudo
LordJudo chooses mars  as their active house this turn
Main phase - LordJudo
LordJudo plays Airlock
LordJudo plays Blypyp
LordJudo plays Mars First
LordJudo gains an Æmber  due to Mars First's bonus icon
LordJudo uses Mars First to ready and use Blypyp
LordJudo uses Blypyp to reap with Blypyp
LordJudo uses Blypyp to make the next Mars  creature played this turn enter play ready
 Mapo174 has joined the game as a spectator
Ready phase - LordJudo
LordJudo readies their cards 
Draw phase - LordJudo
LordJudo draws 3 card  s to their maximum of 6
End of turn 2
LordJudo: 2 Æmber  (0 keys) TomG_LordJudo: 1 Æmber  (0 keys)
TURN 2 - TomG_LordJudo
Key phase - TomG_LordJudo
TomG_LordJudo does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - TomG_LordJudo
TomG_LordJudo chooses geistoid  as their active house this turn
Main phase - TomG_LordJudo
 TomG_LordJudo is attempting to switch manual mode on
 LordJudo allows enabling manual mode
 TomG_LordJudo switches manual mode on
 TomG_LordJudo manually changed their active house to untamed 
 LordJudo switches manual mode off
TomG_LordJudo plays Blernean Hydra
TomG_LordJudo discards Return to Rubble due to Blernean Hydra's bonus icon
TomG_LordJudo plays Dew Faerie
TomG_LordJudo plays Gravid Cycle
TomG_LordJudo gains an Æmber  due to Gravid Cycle's bonus icon
TomG_LordJudo uses Gravid Cycle to return Invigorating Shower to their hand
TomG_LordJudo played Gravid Cycle which has Omega, ending this step
Ready phase - TomG_LordJudo
TomG_LordJudo readies their cards 
Draw phase - TomG_LordJudo
TomG_LordJudo draws 3 card  s to their maximum of 6
End of turn 2
LordJudo: 2 Æmber  (0 keys) TomG_LordJudo: 2 Æmber  (0 keys)
TURN 3 - LordJudo
Key phase - LordJudo
LordJudo does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - LordJudo
 Mapo174 has left the game
 TomG_LordJudo has disconnected. The game will wait up to 30 seconds for them to reconnect
 TomG_LordJudo has reconnected
 TomG_LordJudo has connected to the game server
 LordJudo has disconnected. The game will wait up to 30 seconds for them to reconnect
 LordJudo has reconnected
 LordJudo has connected to the game server
LordJudo chooses untamed  as their active house this turn
Main phase - LordJudo
LordJudo plays Grave Pixie
LordJudo gains an Æmber  due to Grave Pixie's bonus icon
LordJudo plays Skeletal Murmook
LordJudo discards Invigorating Shower
LordJudo discards Spoo-key Charge
LordJudo uses Loyal Packmate to reap with Loyal Packmate
Ready phase - LordJudo
LordJudo readies their cards 
Draw phase - LordJudo
LordJudo draws 4 card  s to their maximum of 6
End of turn 3
LordJudo: 4 Æmber  (0 keys) TomG_LordJudo: 2 Æmber  (0 keys)
TURN 3 - TomG_LordJudo
Key phase - TomG_LordJudo
TomG_LordJudo does not forge a key. They have 2 amber. The current cost is 6 Æmber 
House phase - TomG_LordJudo

**Comment by strib** [comment]
Should be good on the dev server now.
