### ISSUE TITLE
Body Snatchers and Big One - I took control of his artifacts too. 

### ISSUE THREAD

**Issue by tobinlopes** [keyteki/keyteki#3897]
Log follows screen shot. 

Justice had a lot of artifacts out. Big one, on my side, had 9 counters. I played some Mars cards including Body Snatchers. I played my Mars creature and triggered Big one to destroy everything. I got control of all artifacts as well as his three creatures. 

![image](https://github.com/keyteki/keyteki/assets/3495881/bf615236-a0ed-427d-9303-f26b316d89af)

Justice_Atila brings Sierva la Frágil to The Crucible
tobinlopes brings M. Horton, the Bath Carpenter to The Crucible
Justice_Atila won the flip and is first player
 Justice_Atila has connected to the game server
 tobinlopes has connected to the game server
Justice_Atila is shuffling their deck
Justice_Atila draws 6 card  s to their maximum of 6
tobinlopes is shuffling their deck
tobinlopes draws 6 card  s to their maximum of 6
Justice_Atila draws 1 card 
tobinlopes
Enjoy!
Justice_Atila
GL
Key phase - Justice_Atila
Justice_Atila does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Justice_Atila
Justice_Atila chooses logos  as their active house this turn
Main phase - Justice_Atila
Justice_Atila plays Labwork
Justice_Atila gains an Æmber  due to Labwork's bonus icon
Justice_Atila uses Labwork to archive a card 
Ready phase - Justice_Atila
Draw phase - Justice_Atila
Justice_Atila draws 1 card  to their maximum of 6
End of turn 1
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 0 Æmber  (0 keys)
TURN 1 - tobinlopes
Key phase - tobinlopes
tobinlopes does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - tobinlopes
tobinlopes chooses brobnar  as their active house this turn
Main phase - tobinlopes
tobinlopes plays Rickety Cybergiant
tobinlopes plays Ornar Skullface
tobinlopes plays Ornar Skullface
tobinlopes plays Down To Size
tobinlopes gains an Æmber  due to Down To Size's bonus icon
Ready phase - tobinlopes
tobinlopes readies their cards 
Draw phase - tobinlopes
tobinlopes draws 4 card  s to their maximum of 6
End of turn 1
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 1 Æmber  (0 keys)
TURN 2 - Justice_Atila
Key phase - Justice_Atila
Justice_Atila does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Justice_Atila
Justice_Atila chooses sanctum  as their active house this turn
Main phase - Justice_Atila
Justice_Atila plays Haedroth’s Wall
Justice_Atila plays Haedroth’s Wall
Justice_Atila plays Hallowed Shield
Justice_Atila plays Challe the Safeguard
Ready phase - Justice_Atila
Justice_Atila readies their cards 
Draw phase - Justice_Atila
Justice_Atila draws 4 card  s to their maximum of 6
End of turn 2
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 1 Æmber  (0 keys)
TURN 2 - tobinlopes
Key phase - tobinlopes
tobinlopes does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - tobinlopes
tobinlopes chooses brobnar  as their active house this turn
Main phase - tobinlopes
tobinlopes plays Brikk Nastee
tobinlopes plays The Big One
tobinlopes gains an Æmber  due to The Big One's bonus icon
tobinlopes uses Rickety Cybergiant to make Rickety Cybergiant fight Challe the Safeguard
tobinlopes uses Brikk Nastee to gain 1 Æmber 
tobinlopes uses Rickety Cybergiant to deal damage to Rickety Cybergiant
tobinlopes uses Ornar Skullface to reap with Ornar Skullface
tobinlopes uses Ornar Skullface to reap with Ornar Skullface
Ready phase - tobinlopes
tobinlopes readies their cards 
Draw phase - tobinlopes
tobinlopes draws 2 card  s to their maximum of 6
End of turn 2
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 5 Æmber  (0 keys)
TURN 3 - Justice_Atila
Key phase - Justice_Atila
Justice_Atila does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Justice_Atila
Justice_Atila chooses logos  as their active house this turn
Main phase - Justice_Atila
Justice_Atila plays [REDACTED]
Justice_Atila plays Pocket Universe
Justice_Atila plays Jargogle
tobinlopes uses The Big One to place 1 fuse on The Big One
Justice_Atila uses Jargogle to place a card  under Jargogle
Ready phase - Justice_Atila
Justice_Atila readies their cards 
Draw phase - Justice_Atila
Justice_Atila draws 4 card  s to their maximum of 6
End of turn 3
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 5 Æmber  (0 keys)
TURN 3 - tobinlopes
Key phase - tobinlopes
tobinlopes does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - tobinlopes
tobinlopes chooses untamed  as their active house this turn
Main phase - tobinlopes
tobinlopes plays Æmber Storm
tobinlopes gains an Æmber  due to Æmber Storm's bonus icon
tobinlopes uses Æmber Storm to deal 1 damage to an enemy creature for each Æmber  in their pool
Justice_Atila uses Jargogle to archive a card 
tobinlopes plays Dharna
tobinlopes uses Dharna to gain 1 Æmber 
tobinlopes uses The Big One to place 1 fuse on The Big One
tobinlopes plays The Circle of Life
tobinlopes gains an Æmber  due to The Circle of Life's bonus icon
tobinlopes uses The Circle of Life to make each haunted player gain 2 Æmber 
Ready phase - tobinlopes
tobinlopes readies their cards 
Draw phase - tobinlopes
tobinlopes draws 3 card  s to their maximum of 6
 tobinlopes declares Check!
End of turn 3
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 8 Æmber  (0 keys)
TURN 4 - Justice_Atila
Key phase - Justice_Atila
Justice_Atila does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Justice_Atila
Justice_Atila chooses sanctum  as their active house this turn
Main phase - Justice_Atila
Justice_Atila plays Proclamation 346E
Justice_Atila plays Lord Golgotha
tobinlopes uses The Big One to place 1 fuse on The Big One
Justice_Atila plays Sir Marrows
tobinlopes uses The Big One to place 1 fuse on The Big One
Justice_Atila plays Abond the Armorsmith
tobinlopes uses The Big One to place 1 fuse on The Big One
Ready phase - Justice_Atila
Justice_Atila readies their cards 
Draw phase - Justice_Atila
Justice_Atila draws 4 card  s to their maximum of 6
End of turn 4
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 8 Æmber  (0 keys)
TURN 4 - tobinlopes
Key phase - tobinlopes
tobinlopes forges the blue key  , paying 8 Æmber 
House phase - tobinlopes
tobinlopes chooses brobnar  as their active house this turn
Main phase - tobinlopes
tobinlopes uses Rickety Cybergiant to reap with Rickety Cybergiant
Justice_Atila uses Sir Marrows to capture 1 Æmber 
tobinlopes uses Ornar Skullface to make Ornar Skullface fight Sir Marrows
tobinlopes uses Ornar Skullface to deal 3 damage to Sir Marrows
tobinlopes uses Brikk Nastee to gain 1 Æmber 
tobinlopes uses Ornar Skullface to make Ornar Skullface fight Abond the Armorsmith
tobinlopes uses Ornar Skullface to deal 3 damage to Abond the Armorsmith
tobinlopes uses Brikk Nastee to gain 1 Æmber 
tobinlopes plays Fight to the End
tobinlopes gains an Æmber  due to Fight to the End's bonus icon
tobinlopes uses Fight to the End to ready and fight with Rickety Cybergiant
tobinlopes uses Rickety Cybergiant to make Rickety Cybergiant fight Lord Golgotha
tobinlopes uses Brikk Nastee to gain 1 Æmber 
tobinlopes plays Raider of the Peaks
tobinlopes uses The Big One to place 1 fuse on The Big One
tobinlopes uses Brikk Nastee to reap with Brikk Nastee
Ready phase - tobinlopes
tobinlopes readies their cards 
Draw phase - tobinlopes
tobinlopes draws 2 card  s to their maximum of 6
End of turn 4
Justice_Atila: 1 Æmber  (0 keys) tobinlopes: 6 Æmber  (1 key)
TURN 5 - Justice_Atila
Key phase - Justice_Atila
Justice_Atila does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Justice_Atila
Justice_Atila chooses untamed  as their active house this turn
Main phase - Justice_Atila
Justice_Atila plays Regrowth
Justice_Atila gains an Æmber  due to Regrowth's bonus icon
Justice_Atila uses Regrowth to return Lord Golgotha to their hand
Justice_Atila plays Marmo Swarm
tobinlopes uses The Big One to place 1 fuse on The Big One
Justice_Atila plays Marmo Swarm
tobinlopes uses The Big One to place 1 fuse on The Big One
Justice_Atila uses Mimicry to to copy Down To Size
Justice_Atila plays Mimicry
Justice_Atila gains an Æmber  due to Mimicry's bonus icon
Justice_Atila uses Mimicry to make Ornar Skullface have 1 power and 0 amor until the end of the turn
Justice_Atila plays Dharna
tobinlopes uses The Big One to place 1 fuse on The Big One
Ready phase - Justice_Atila
Justice_Atila readies their cards 
Draw phase - Justice_Atila
Justice_Atila draws 4 card  s to their maximum of 6
End of turn 5
Justice_Atila: 3 Æmber  (0 keys) tobinlopes: 6 Æmber  (1 key)
TURN 5 - tobinlopes
tobinlopes uses Raider of the Peaks to make Justice_Atila discard the top card  of their deck
Key phase - tobinlopes
tobinlopes does not forge a key. They have 6 amber. The current cost is 8 Æmber 
House phase - tobinlopes
tobinlopes chooses mars  as their active house this turn
Main phase - tobinlopes
tobinlopes plays Big Magnet
tobinlopes gains an Æmber  due to Big Magnet's bonus icon
tobinlopes plays Braindart
tobinlopes gains an Æmber  due to Braindart's bonus icon
tobinlopes uses Braindart to enrage Dharna and make it capture 1 Æmber  from its own side
tobinlopes plays The Body Snatchers
tobinlopes uses The Body Snatchers to give each enemy creature 'Destroyed: Fully heal this creature and give control of it to your opponent instead' for the remainder of the turn
tobinlopes plays Don’t Believe Your Eyes
tobinlopes uses Don’t Believe Your Eyes to capture 2 Æmber  from Justice_Atila, placing it on Marmo Swarm
tobinlopes plays Yipyax Abductor
tobinlopes uses The Big One to place 1 fuse on The Big One
The Big One has 10 fuse counters and destroys all creatures and artifacts
Justice_Atila uses Proclamation 346E to heal all damage from Proclamation 346E and give control to tobinlopes
Justice_Atila uses Pocket Universe to heal all damage from Pocket Universe and give control to tobinlopes
Justice_Atila uses [REDACTED] to heal all damage from [REDACTED] and give control to tobinlopes
Justice_Atila uses Hallowed Shield to heal all damage from Hallowed Shield and give control to tobinlopes
Justice_Atila uses Haedroth’s Wall to heal all damage from Haedroth’s Wall and give control to tobinlopes
Justice_Atila uses Haedroth’s Wall to heal all damage from Haedroth’s Wall and give control to tobinlopes
Justice_Atila uses Dharna to heal all damage from Dharna and give control to tobinlopes
Justice_Atila uses Marmo Swarm to heal all damage from Marmo Swarm and give control to tobinlopes
Justice_Atila uses Marmo Swarm to heal all damage from Marmo Swarm and give control to tobinlopes
tobinlopes
huh?
Justice_Atila
WTF
tobinlopes
a bug in TCO
tobinlopes
I was supposed to take control of your creatures, not your artifacts!
tobinlopes
ok. gg.!
tobinlopes
lol

**Comment by UltimoFox** [comment]
Same thing just happened to me - except upgrades were ALSO affected, which made things weird.

They hit my Little Niff, Seeker Needle, and Officer's Blaster with Destroy Them All!, which made TCO try and take control of all 3 cards - since the upgrade remains attached to the creature it was on, the control swapping failed and the card remained in play instead of being destroyed. Ended up making a mess of a gamestate...here's a screenshot of the event and a gamelog posted below:
![image](https://github.com/user-attachments/assets/36f55c37-b886-467c-af43-2f62299f92e0)

Harmed brings Ancillary “No Mercy” Kyell to The Crucible
UltimoFox brings Seneschal H. I. Shipwreck to The Crucible
UltimoFox won the flip and is first player
 Harmed has connected to the game server
 UltimoFox has connected to the game server
Harmed is shuffling their deck
Harmed draws 6 card  s to their maximum of 6
UltimoFox is shuffling their deck
UltimoFox draws 6 card  s to their maximum of 6
UltimoFox draws 1 card 
Harmed
Hi there! GL and HF :)
UltimoFox
Just to double check, this is simply a Bo1 game, correct?
Harmed
yes it is
UltimoFox
It's only my second game in the Snake and my first was weeks ago now haha
UltimoFox
Perfect! Thanks :)
UltimoFox
GL & HF!
Harmed
Haha
Harmed
You too!
Key phase - UltimoFox
UltimoFox does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - UltimoFox
UltimoFox chooses staralliance  as their active house this turn
Main phase - UltimoFox
UltimoFox plays Agent Sepdia
Ready phase - UltimoFox
UltimoFox readies their cards 
Draw phase - UltimoFox
UltimoFox draws 1 card  to their maximum of 6
End of turn 1
Harmed: 0 Æmber  (0 keys) UltimoFox: 0 Æmber  (0 keys)
TURN 1 - Harmed
Key phase - Harmed
Harmed does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - Harmed
Harmed chooses geistoid  as their active house this turn
Main phase - Harmed
Harmed plays Junk Restoration
Harmed gains an Æmber  due to Junk Restoration's bonus icon
Harmed uses Junk Restoration to discard Cursed Relic, Phloxem Spike, and Aerial Pedlar
Harmed plays Titan Apparition
Harmed plays Colonel Slime
Ready phase - Harmed
Harmed readies their cards 
Draw phase - Harmed
Harmed draws 4 card  s to their maximum of 6
End of turn 1
Harmed: 1 Æmber  (0 keys) UltimoFox: 0 Æmber  (0 keys)
TURN 2 - UltimoFox
Key phase - UltimoFox
UltimoFox does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - UltimoFox
UltimoFox chooses staralliance  as their active house this turn
Main phase - UltimoFox
UltimoFox plays Technobabble
UltimoFox gains an Æmber  due to Technobabble's bonus icon
UltimoFox uses Technobabble to stun Titan Apparition and Colonel Slime
UltimoFox uses Agent Sepdia to reap with Agent Sepdia
UltimoFox uses Agent Sepdia to deal 1 damage to Titan Apparition
Ready phase - UltimoFox
UltimoFox readies their cards 
Draw phase - UltimoFox
UltimoFox draws 1 card  to their maximum of 6
End of turn 2
Harmed: 1 Æmber  (0 keys) UltimoFox: 2 Æmber  (0 keys)
TURN 2 - Harmed
Key phase - Harmed
Harmed does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - Harmed
Harmed chooses ekwidon  as their active house this turn
Main phase - Harmed
Harmed discards De-escalation
Harmed plays Reap the Wild Wind
Harmed gains an Æmber  due to Reap the Wild Wind's bonus icon
Harmed discards Zizok due to Reap the Wild Wind's bonus icon
Harmed uses Reap the Wild Wind to reveal a random card  from each player's hand
Reap the Wild Wind reveals Watney’s Calculation
Reap the Wild Wind reveals Abyssal Zealot
Harmed uses Reap the Wild Wind to gain 2 amber, and UltimoFox gains 0 Æmber 
Harmed plays Vendor Hyertula
Harmed gains an Æmber  due to Vendor Hyertula's bonus icon
Harmed plays Outnegotiate
Harmed gains an Æmber  due to Outnegotiate's bonus icon
Harmed captures an Æmber  on Colonel Slime due to Outnegotiate's bonus icon
Harmed discards Watney’s Calculation due to Outnegotiate's bonus icon
Harmed uses Outnegotiate to steal 1 Æmber  from UltimoFox
Harmed uses Outnegotiate to return Technobabble to the bottom of their owner's deck
Ready phase - Harmed
Harmed readies their cards 
Draw phase - Harmed
Harmed draws 6 card  s to their maximum of 6
 Harmed declares Check!
End of turn 2
Harmed: 7 Æmber  (0 keys) UltimoFox: 0 Æmber  (0 keys)
TURN 3 - UltimoFox
Key phase - UltimoFox
UltimoFox does not forge a key. They have 0 amber. The current cost is 6 Æmber 
House phase - UltimoFox
UltimoFox chooses unfathomable  as their active house this turn
Main phase - UltimoFox
UltimoFox plays Mælstrom
UltimoFox uses Mælstrom to randomly put each creature on top of its owner's deck and gain 2 chains
UltimoFox plays Abyssal Zealot
UltimoFox plays Brain Drain
UltimoFox gains an Æmber  due to Brain Drain's bonus icon
UltimoFox uses Brain Drain to return Summoned Counsel to the top of their owner's deck
UltimoFox changed tide  to High
UltimoFox uses Abyssal Zealot to capture 2 Æmber  from their opponent , placing it on Abyssal Zealot
UltimoFox plays Pour-tal
UltimoFox gains an Æmber  due to Pour-tal's bonus icon
UltimoFox uses Pour-tal to archive itself
Ready phase - UltimoFox
UltimoFox readies their cards 
Draw phase - UltimoFox
UltimoFox draws 3 card  s to their maximum of 6
UltimoFox's chains are reduced by 1 to 4
End of turn 3
Harmed: 5 Æmber  (0 keys) UltimoFox: 3 Æmber  (0 keys)
TURN 3 - Harmed
Key phase - Harmed
Harmed does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - Harmed
Harmed
Thats a lot of chains!
Harmed chooses ekwidon  as their active house this turn
Main phase - Harmed
Harmed plays Distributor Janŏŏnt
Harmed discards Summoned Counsel due to Distributor Janŏŏnt's bonus icon
Harmed plays Reap the Wild Wind
Harmed gains an Æmber  due to Reap the Wild Wind's bonus icon
Harmed uses Reap the Wild Wind to reveal a random card  from each player's hand
Reap the Wild Wind reveals Harvest Skimmer
Reap the Wild Wind reveals One-Eyed Willa
Harmed uses Reap the Wild Wind to gain 1 amber, and UltimoFox gains 0 Æmber 
Ready phase - Harmed
Harmed readies their cards 
Draw phase - Harmed
Harmed draws 4 card  s to their maximum of 6
 Harmed declares Check!
End of turn 3
Harmed: 7 Æmber  (0 keys) UltimoFox: 3 Æmber  (0 keys)
TURN 4 - UltimoFox
Key phase - UltimoFox
UltimoFox does not forge a key. They have 3 amber. The current cost is 6 Æmber 
House phase - UltimoFox
UltimoFox
Isn't that a tiebreaker? Most chains in a turn?
Harmed
xD
UltimoFox chooses shadows  as their active house this turn
Main phase - UltimoFox
UltimoFox plays Shoulder Id
UltimoFox plays Gas-Pipes Malone
UltimoFox plays One-Eyed Willa
Ready phase - UltimoFox
UltimoFox readies their cards 
Draw phase - UltimoFox
UltimoFox draws 3 card  s to their maximum of 6
UltimoFox's chains are reduced by 1 to 3
End of turn 4
Harmed: 7 Æmber  (0 keys) UltimoFox: 3 Æmber  (0 keys)
TURN 4 - Harmed
Key phase - Harmed
Harmed forges the yellow key  , paying 6 Æmber 
House phase - Harmed
Harmed chooses geistoid  as their active house this turn
Main phase - Harmed
Harmed plays Titan Apparition
Harmed plays Summoned Counsel
Harmed gains an Æmber  due to Summoned Counsel's bonus icon
Harmed gains an Æmber  due to Summoned Counsel's bonus icon
Harmed plays Harvest Skimmer
Harmed gains an Æmber  due to Harvest Skimmer's bonus icon
Harmed captures an Æmber  on Distributor Janŏŏnt due to Harvest Skimmer's bonus icon
Harmed captures an Æmber  on Summoned Counsel due to Harvest Skimmer's bonus icon
Harmed plays Colonel Slime
Ready phase - Harmed
Harmed readies their cards 
Draw phase - Harmed
Harmed draws 4 card  s to their maximum of 6
End of turn 4
Harmed: 4 Æmber  (1 key) UltimoFox: 1 Æmber  (0 keys)
TURN 5 - UltimoFox
Key phase - UltimoFox
UltimoFox does not forge a key. They have 1 amber. The current cost is 6 Æmber 
House phase - UltimoFox
UltimoFox chooses staralliance  as their active house this turn
Main phase - UltimoFox
UltimoFox plays Agent Sepdia
UltimoFox plays Officer’s Blaster attaching it to Gas-Pipes Malone
UltimoFox gains an Æmber  due to Officer’s Blaster's bonus icon
UltimoFox plays Shield-U-Later attaching it to Gas-Pipes Malone
UltimoFox plays Zap
UltimoFox gains an Æmber  due to Zap's bonus icon
UltimoFox uses Zap to deal 1 damage to a creature for each house represented among creatures in play
Ready phase - UltimoFox
UltimoFox readies their cards 
Draw phase - UltimoFox
UltimoFox draws 4 card  s to their maximum of 6
UltimoFox's chains are reduced by 1 to 2
End of turn 5
Harmed: 4 Æmber  (1 key) UltimoFox: 5 Æmber  (0 keys)
TURN 5 - Harmed
Key phase - Harmed
Harmed does not forge a key. They have 4 amber. The current cost is 6 Æmber 
House phase - Harmed
Harmed chooses geistoid  as their active house this turn
Main phase - Harmed
Harmed plays Wellstring
Harmed gains an Æmber  due to Wellstring's bonus icon
Harmed plays Haunting Deck
Harmed gains an Æmber  due to Haunting Deck's bonus icon
Harmed captures an Æmber  on Colonel Slime due to Haunting Deck's bonus icon
Harmed uses Haunting Deck to purge Cursed Relic
Harmed uses Harvest Skimmer to reap with Harvest Skimmer
Harmed uses Harvest Skimmer to discard Crystal Hive
Harmed uses Titan Apparition to make Titan Apparition fight Shoulder Id
Harmed uses Colonel Slime to make Colonel Slime fight Abyssal Zealot
Ready phase - Harmed
Harmed readies their cards 
Draw phase - Harmed
Harmed draws 2 card  s to their maximum of 6
 Harmed declares Check!
End of turn 5
Harmed: 8 Æmber  (1 key) UltimoFox: 5 Æmber  (0 keys)
TURN 6 - UltimoFox
Key phase - UltimoFox
UltimoFox does not forge a key. They have 5 amber. The current cost is 6 Æmber 
House phase - UltimoFox
UltimoFox chooses shadows  as their active house this turn
Main phase - UltimoFox
UltimoFox uses One-Eyed Willa to make One-Eyed Willa fight Colonel Slime
UltimoFox uses One-Eyed Willa to steal 1 Æmber  from Harmed
UltimoFox uses Gas-Pipes Malone to make Gas-Pipes Malone fight Titan Apparition
UltimoFox uses Gas-Pipes Malone to capture 1 Æmber  from Harmed, placing it on Titan Apparition
Harmed uses Titan Apparition to discard Blatant Thievery, Abandon Ship, Call of the Void, Cement Shoes, and Tidal Wave
UltimoFox plays Seeker Needle
UltimoFox plays Gas-Pipes Malone
UltimoFox plays Little Niff
UltimoFox played Little Niff which has Omega, ending this step
Ready phase - UltimoFox
UltimoFox readies their cards 
Draw phase - UltimoFox
UltimoFox draws 3 card  s to their maximum of 6
UltimoFox's chains are reduced by 1 to 1
 UltimoFox declares Check!
End of turn 6
Harmed: 6 Æmber  (1 key) UltimoFox: 8 Æmber  (0 keys)
TURN 6 - Harmed
Key phase - Harmed
Harmed forges the blue key  , paying 6 Æmber 
House phase - Harmed
Harmed chooses mars  as their active house this turn
Main phase - Harmed
Harmed plays The Body Snatchers
Harmed gains an Æmber  due to The Body Snatchers's bonus icon
Harmed uses The Body Snatchers to give each enemy creature 'Destroyed: Fully heal this creature and give control of it to your opponent instead' for the remainder of the turn
Harmed plays Destroy Them All!
UltimoFox
Oh dear
Harmed uses Destroy Them All! to destroy Seeker Needle, Little Niff, and Officer’s Blaster
UltimoFox uses Seeker Needle to heal all damage from Seeker Needle and give control to Harmed
UltimoFox uses Little Niff to heal all damage from Little Niff and give control to Harmed
UltimoFox uses Officer’s Blaster to heal all damage from Officer’s Blaster and give control to Harmed
Harmed
Wait what?
Harmed
Lol
UltimoFox
Uhhhhh that doesn't seem right
Harmed
Heal all damage from Officer's blaster? How does that work? xD
Harmed
And I have a seeker needle, wtf?
UltimoFox
Yeah that's exceptionally strange
Harmed
I believe the malone with upgrades should be dead
UltimoFox
Definitely worth submitting this game as a support ticket in TCO's github
Harmed
and the needle gone
Harmed plays Cobalt Kapulet
UltimoFox
Yeah, The Body Snatchers is definitely messing things up
Harmed
Want to fix it?
UltimoFox
Let me take some screenshots and submit the bug, then we can fix the gamestate with Manual Mode
Harmed
Sounds good
Harmed
Ready?
