### ISSUE TITLE
Chat log says Epic Quest is triggering on 6 cards

### ISSUE THREAD

**Issue by Tutenkharnage** [keyteki/keyteki#3958]
From the chat log:

_Tutenkharnage uses Epic Quest to forge a key if 6 or more sanctum  cards  were played this turn_

No idea whether it's actually triggering on six; I used EQ's Omni ability on an Untamed turn, just to be cheeky.

**Comment by dlocke** [comment]
The log is technically correct. You used EQ and it will forge a key **if** six or more Sanctum cards were played this turn. It's an Untamed turn, so you probably haven't played six Sanctum cards.

Because EQ is an Omni, it's possible to play six Sanctum cards on a Logos turn and then use EQ to forge.

**Comment by Tutenkharnage** [comment]
The problem is that Epic Quest is only supposed to forge a key if **seven** or more Sanctum cards are played in a turn, not six. I don't know whether the card actually forged a free key if you only play six cards, but the chat log suggests that it does.

**Comment by strib** [comment]
Fixed in #4302 .
