### ISSUE TITLE
Invigorating Shower does not shuffle deck when you name a house that isn't in the discard pile

### ISSUE THREAD

**Issue by mcarulli** [keyteki/keyteki#3960]
Easy to tell when you have Near-Future Lens on table. Such as with this deck:
https://decksofkeyforge.com/decks/f88da7de-4bb5-40b0-a646-728238290dce

1. See what the top card is with NFL
2. Play Invigorating shower and name a house that has 0 cards in your discard pile

Expected behavior: Should shuffle your deck and reveal a new card with NFL
Actual Behavior: Prompt does not shuffle and just says 
"quickdraw3457 chooses house shadows 
quickdraw3457 uses Invigorating Shower"

**Comment by strib** [comment]
Works fine with that deck for me.  Not sure what happened for you, next time it happens please provide a full log.  Closing for now.

![image](https://github.com/user-attachments/assets/e9a79b10-5284-4353-bd39-6a061795aa20)

**Comment by mcarulli** [comment]
@strib was able to easily reproduce. see screenshot and game log. 
<img width="153" alt="Screenshot 2024-09-02 212649" src="https://github.com/user-attachments/assets/8013abde-5140-4963-b5d7-18ecd0cfde15">
[invigorating shower bug.txt](https://github.com/user-attachments/files/16842341/invigorating.shower.bug.txt)

**Comment by strib** [comment]
Thanks.  As discussed on Discord, maybe I do see the bug.  I think weirdly it happens if your opponent's discard is empty when you play the card, and it actually shuffles your opponent's deck instead of yours in that case.  (I have been testing in manual mode without an opponent, so I couldn't repro it, and it explains why Till the Earth affects it.)

It's a bug in `ReturnToDeckAction` if I'm right.  Will try to look into it when I have time ... some day...
