### ISSUE TITLE
Aember Conduction Unit Bug

### ISSUE THREAD

**Issue by justicewebtech** [keyteki/keyteki#410]
Aember Conduction Unit didn't stun all creatures that reaped in this turn. 

Plays Pile of Skulls
Plays Hebe the Huge
Uses Hebe the Huge to deal 2 damage to each undamaged creature
Uses Krump to reap with Krump
Uses Æmber Conduction Unit to stun Krump
Uses Containment Field to destroy Krump
Uses Ganger Chieftain to reap with Ganger Chieftain
Uses Smaaash to reap with Smaaash
Uses Krump to reap with Krump
Plays Relentless Assault
Uses Relentless Assault to ready and fight with Hebe the Huge, Ganger Chieftain, and Smaaash
Uses Hebe the Huge to make Hebe the Huge fight Collector Worm
Uses Pile of Skulls to capture 1 amber from playername, placing it on Smaaash
Uses Ganger Chieftain to make Ganger Chieftain fight The Curator
Uses Pile of Skulls to capture 1 amber from dotbomb, placing it on Ancient Bear
Uses Smaaash to make Smaaash fight Tyxl Beambuckler
Uses Pile of Skulls to capture 1 amber from playername , placing it on Pit Demon
Draws 3 cards

**Comment by Achocholacek** [comment]
ACU does not stun all creatures when they reap, ACU stuns the first creature that reaps in a turn.

Card Text: "After an enemy creature reaps, if it is the first time a creature has reaped this turn, stun it."

So in this example, because Krump was the first creature to reap, he was stunned, and all subsequent reapings would not trigger ACU.

**Comment by justicewebtech** [comment]
Ah, that's what I get for not reading things closely.  Thanks.
