### ISSUE TITLE
Redlock and "Check" timing issue

### ISSUE THREAD

**Issue by cpander129** [keyteki/keyteki#428]
If you get exactly enough aember with Redlock's end of turn effect there is no "Check" notification in chat. With a little testing it seems that the "Check" check fires before Redlock does.

**Comment by romanogit** [comment]
@jeremylarner :

consider the DrawPhase class bellow. I believe the roundEnded should simply call game.endRound(). The other statements, such as changing the activer player and resetting the active house should be done in game.endRound(). I say that because if there is any card that still needs to use the activeHouse, it would be null. For example, let's say Redlocks had a condition like "if no creature from the active house", the engine would need the active house in the onRoundEnded event handler. But it is quite curious that resetting the active house is right before calling game.endround().

```java
const Phase = require('../phase.js');
const SimpleStep = require('../simplestep.js');

class DrawPhase extends Phase {
    constructor(game) {
        super(game, 'draw');
        this.initialise([
            new SimpleStep(game, () => this.drawCards()),
            new SimpleStep(game, () => this.roundEnded())
        ]);
    }

    drawCards() {
        let player = this.game.activePlayer;
        let amount = player.maxHandSize - player.hand.length;
        if(amount > 0) {
            this.game.addMessage('{0} draws {1} cards up to their maximum hand size of {2}', player, amount, player.maxHandSize);
        }

        this.game.actions.draw({ amount: amount, shedChains: true }).resolve(player, this.game.getFrameworkContext());

        if(player.canForgeKey()) {
            this.game.addAlert('success', '{0} declares Check!', player);
        }
    }

    roundEnded() {
        this.game.raiseEvent('onRoundEnded', {}, () => {
            this.game.activePlayer.activeHouse = null;
            this.game.endRound();
            if(this.game.activePlayer.opponent) {
                this.game.activePlayer = this.game.activePlayer.opponent;
            }
        });
    }
}

module.exports = DrawPhase;

```

**Comment by romanogit** [comment]
@Dicky-Boy ,

I thought about this fix the you did, however, we may have some issues with it. The card says, at the end of your turn, not at the end of the main phase. Thus, technically, it should collect the amber right after the draw phase. 

Maybe, right now, no card effect is affected by this, but we could, technically, in the future. Creating a pull request is an alternative solution, if you don't mind.
