### ISSUE TITLE
Stealer of Souls and Bad Penny: game message says 'purge and gain 1 amber'

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#496]
Stealer of Souls and Bad Penny: game message says 'purge and gain 1 amber', but bad penny is never purged.

maybe it should say "attempt to purge Bad Penny, and gain 1 amber'

**Comment by JTLSound** [comment]
I don't think this is what is happening, according to the game state/rules. 

Stealer of Souls deals damage to Bad Penny, Bad Penny is marked for destruction. Bad Penny's Destroyed effect triggers, removing it from play to owner's hand. Stealer of Souls' effect triggers because a creature was destroyed fighting it. You purge nothing, because nothing is there, and gain 1 aember. "No creature to purge" would make more sense imo.

**Comment by romanogit** [comment]
Closing, as this is a very minor issue and, in theory, even for Bad Penny that message could still be valid. Bad Penny, at the end, returns to owners hand anyway.
