### ISSUE TITLE
Rules question: taunt and damage-dealing before fight abilities

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#594]
Currently, when the declared target of a fight becomes the neighbor of a taunt creature after declaring a fight, but before the fight damage is dealt, no fight damage is dealt. I don't have any screenshots but I've seen this enough times now that I know this will always happen

As an example of what I'm talking about, opponent has an umbra, a shadows ambassador and a challe the safeguard in that order and I use a cowfyne to attack the umbra. In this situation the before fight ability will trigger and destroy the ambassador, but then, with how TCO is currently coded, the fight will be over. Because when the actual fight is supposed to happen, the umbra will have become a neighbor of a taunt creature. So probably the system thinks it should not be a valid target of a fight. 

I think this is incorrect.

From rules for fighting: 

"When a player uses a creature to fight, the player exhausts the creature and chooses an opponent’s creature. Both creatures deal an amount of damage equal to their power value to the opposing creature in the fight, and both are “fighting” for the purposes of card effects."

From rules for taunt: 

"If a creature has the taunt keyword, any of its neighbors that do not have the taunt keyword cannot be attacked by an enemy creature that is being used to fight.In the battleline, taunt creatures are slid slightly forward to indicate their presence to the opponent."

The way I read the above, the neighor of a taunt creature cannot be attacked by a creature which is being used to fight. The way I read the fight rules is that the target of the fight is being chosen WHEN THE ATTACKING CREATURE IS EXHAUSTED AND USED TO FIGHT. It is at this time, and this time only, that a creature can be protected by a neighboring taunt creature. If it later receives a taunt creature as a neighbor, you shouldn't go back in time and cancel the fight. Still, this is my opinion, and to know for certain we would need an FAQ entry from FFG

**Comment by Achocholacek** [comment]
I certainly understand your argument and see validity in it, but I would interpret the sequence of events as follows (which leads to a slightly different outcome than you)

1) Choose to fight Umbra with Cowfyne
2) Cowfyne Exhausts
3) Cowfyne's Before Fight: ability triggers, which destroys the Ambassador. 
4) Before Fight resolves, and Ambassador leaves play. 
5) Umbra slides in next to Challe and becomes untargetable due to Taunt (which will still apply as neither Umbra nor Challe have been marked for destruction, therefore Challe can still affect Umbra)
6) The fight then happens as if Cowfyne had chosen to attack Challe instead, because Umbra was unable to be chosen as a target.

(I think you're correct about TCO currently, which would make Step 6 "The fight fizzles because Umbra was not a 'valid' target.)

This is a thing we'll definitely need a ruling or a faq on before adjusting.

**Comment by hydrophilic-attack** [comment]
So there is an email rules question ruling supporting the argument I made:

"Imagine the example battle line: Champion Anaphiel, Commander Ramiel, Ember Imp

Ramiel is protected by Anapheil’s taunt. Lord Golgotha attacks Ember Imp. The “before fight” ability deals 3 damage to Ramiel, destroying it. Now Ember Imp is neighboring Anaphiel. Does the fight continue as Ember Imp was a valid target when it was attacked? Or is Ember Imp now protected by Taunt, leaving Golgotha exhausted and no fight occurring?

Their response was that the fight would continue as normal:

The fight will continue as normal, with Lord Golgotha attacking Ember Imp.The Taunt keyword only protects a creature at the time the opponent is choosing which creature to attack—it doesn’t retroactively invalidate a fight in this situation.

I'll edit with a link to the reddit thread
