### ISSUE TITLE
general order 24

### ISSUE THREAD

**Issue by brookslclark** [keyteki/keyteki#724]
my opponent had no creatures in play and general order 24 didnt sac, plus once my opponent had creatures and i didnt and it sacd right away should int wait til my turn?

**Comment by SkyJedi** [comment]
![image](https://user-images.githubusercontent.com/2967416/68513484-bec58680-0240-11ea-8dcb-010ad1ca6747.png)

**Comment by bagley2014** [comment]
I had the same problem, where General Order 24 was not destroyed when my opponent had no creatures. We had to destroy it manually.

I didn't grab a screenshot, but the log is here: https://www.thecrucibletracker.com/games/47c0bda0-038c-11ea-91e0-a5a22d3f9d00

On turn 3 I (weather3003) play GO24, and on turn 5 I had to manually destroy it because my opponent had no creatures on their previous turn. The artifact should have been destroyed at the start of turn 5 for my opponent because they had no creatures.
