### ISSUE TITLE
"after a creature reaps" effects maybe do not trigger if the reaping creature has an optional (may) reap ability and active player chooses not to resolve it

### ISSUE THREAD

**Issue by hydrophilic-attack** [keyteki/keyteki#859]
Look at turn 13 in the attached log.

I had a Sir Marrows in play and a pip pip (among other creatures). My opponent reaped first with Rhetor Gallim and chose not to exalt to increase my key cost next turn. Gallim was not stunned and my Sir Marrows did not capture the reaped amber. After that, they reaped with Crassosaurus and the abilities of my Pip Pip and Sir Marrows triggered correctly.

What I suggested in the title is my guess as for why this happened. My guess is that in certain circumstances it's possible that if the active player chooses not to perform a "may" reap ability, other "after a creature reap" effects in play do not correctly trigger. I'm not fully sure if this was the cause though.
[sir marrows pip pip.txt](https://github.com/keyteki/keyteki/files/3832314/sir.marrows.pip.pip.txt)

**Comment by hydrophilic-attack** [comment]
This just happened to me again. I had a paraguardian in play. I chose Logos and played Academy Training on him. Then I reaped and chose not to exalt him. I didn't get to draw a card from the reap ability granted by Academy Training.

So it seems this bug extends to Reap abilities as well

**Comment by romanogit** [comment]
I believe this is already fixed by Timing Refactor and prompt for abilites, but I will double check

**Comment by romanogit** [comment]
As you can see from prompt bellow, you now decide to cancel by clicking on other cards first

![image](https://user-images.githubusercontent.com/2104075/101052673-b041bf80-3565-11eb-975a-309755996ca7.png)

Selected Sir Marrow first:

![image](https://user-images.githubusercontent.com/2104075/101052820-d49d9c00-3565-11eb-84f9-9a63452fb832.png)

Select Pip Pip :

![image](https://user-images.githubusercontent.com/2104075/101052930-f565f180-3565-11eb-8b36-dc50c93e444f.png)

And then I can decide not to exalt:

![image](https://user-images.githubusercontent.com/2104075/101052997-07479480-3566-11eb-84cd-f068918ab7e5.png)

Fixed by Timing Refactor
