### ISSUE TITLE
United Action - Doesn't register new houses that are played after United Action

### ISSUE THREAD

**Issue by GavinForge** [keyteki/keyteki#891]
United Action should allow you to play any house that you have in play for the remainder in the turn, even if the houses in play differs later on in your turn.

I had a board of only Logos and Star Alliance.

Played United Action.

Played Com. Officer Kirby, which allowed me to play an out of house card. I played the Saurian card, The Callipygian Ideal upgrade on a creature

United Action should let me play Saurian cards, but it doesn't.

Turn 15:
https://www.thecrucibletracker.com/games/15217750-05ac-11ea-bf5b-c9306381255f/log

**Comment by pergy** [comment]
I think it's the right thing to do, as United Action is already played, and you won't "re-evalute" its Play ability. That is, when you read a "card in play", that refers to the board state when the ability triggers.

At least, this is the way I see it and couldn't find any official Q&A on the matter yet

**Comment by GavinForge** [comment]
That's fair, it is a bit more ambiguous than what I first read it as.

**Comment by romanogit** [comment]
![image](https://user-images.githubusercontent.com/2104075/68781561-373b9700-05f5-11ea-9f8d-6d82a11473e7.png)

**Comment by romanogit** [comment]
It has room for discussion

**Comment by GavinForge** [comment]
I e-mailed FFG Rules for clarification. Will post if I get an answer.

**Comment by iisfet** [comment]
If i can put my two cents, i'll go with the author. Because even if it is a play effect, it is "for the reminder of the turn", so if at any moment of the turn we check if the condition is true, he can play another logos after kirby. It's like "Song of the wild" if i put in play a ready creature and i reap, even if it was not there when the action was played, i will gain 1 + 1 when i check the action condition. 

Hope you understand me. (i guess the "re-evaualtion" happen continuously during the rest of the turn)
