### ISSUE TITLE
Fangtooth cavern not targeting opppnent creatures

### ISSUE THREAD

**Issue by Adman1138** [keyteki/keyteki#903]
Fangtooth cavern is not letting me target opponent creatures. It should destroy the weakest creature regardless of owner.

**Comment by Dropoint** [comment]
I have also experienced this issue. When Fangtooth Cavern activated at the end of my turn, both myself and the opponent had a creature with power 3 being our least powerful creature. Instead of letting me target which of them would be destroyed, it automatically resolved and destroyed my creature instead of my opponents. I hope that you are able to reproduce this bug somehow and fix it,  otherwise Fangtooth Cavern is a completely dead card in my deck right now unfortunately.

**Comment by Achocholacek** [comment]
I have updated the test spec for this particular case and I still cannot reproduce the issue. If it reoccurs, please provide as much game state information as possible so we can dig deeper. Closing for now.
